const BANKING_SCHEMA_VERSION='1.0';
const BANKING_EXTRA_HEADERS=['source_bancaire','date_comptable','date_achat','libelle_bancaire','marchand_normalise','carte_fin','cle_rapprochement','statut_bancaire'];
const BANKING_BASE_HEADERS=['id','date','libelle','categorie','compte','montant','type','commentaire','cree_le','modifie_le'];
const BANKING_ALL_HEADERS=BANKING_BASE_HEADERS.concat(BANKING_EXTRA_HEADERS);

function normaliserTexteBanqueFiable_(s){return String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').replace(/\s+/g,' ').trim();}
function centimesBanque_(v){return Math.round(Math.abs(Number(v||0))*100);}
function isoJourBanque_(v){if(!v)return'';const d=v instanceof Date?v:new Date(v);if(isNaN(d))return'';return Utilities.formatDate(d,Session.getScriptTimeZone(),'yyyy-MM-dd');}
function dateBanque_(v){if(!v)return'';const d=v instanceof Date?new Date(v):new Date(v);if(isNaN(d))return'';return new Date(d.getFullYear(),d.getMonth(),d.getDate(),12);}
function extraireDateAchatBanque_(texte){const m=String(texte||'').match(/\b(?:CB|PAIEMENT\s+CB|FACTURE\(S\)\s+CARTE[^]*?)\s+DU\s+(\d{2})(\d{2})(\d{2})\b/i)||String(texte||'').match(/^\s*DU\s+(\d{2})(\d{2})(\d{2})\b/i);if(!m)return'';const d=new Date(2000+Number(m[3]),Number(m[2])-1,Number(m[1]),12);return isNaN(d)?'':d;}
function extraireCarteFinBanque_(texte){const m=String(texte||'').match(/(?:CARTE|CARD)\s+\d*[Xx]+(\d{4})\b/);return m?m[1]:'';}
function marchandBanque_(texte,libelle){let s=String(texte||'');s=s.replace(/^\s*(?:PAIEMENT\s+)?CB\s+DU\s+\d{6}\s+/i,'').replace(/^\s*FACTURE\(S\)\s+CARTE[^]*?\s+DU\s+\d{6}\s+/i,'').replace(/^\s*DU\s+\d{6}\s+/i,'');s=s.replace(/\s+CARTE\s+\d*[Xx]+\d{4}.*$/i,'').replace(/\s+(?:FRA|IRL|NLD|ESP|DEU)\s+\d+[,.]\d{2}\s*EUR.*$/i,'').trim();return normaliserTexteBanqueFiable_(s||libelle).slice(0,90);}
function cleBanqueFiable_(o,occurrence,total){const achat=isoJourBanque_(o.date_achat||o.date),compta=isoJourBanque_(o.date_comptable||o.date),c=centimesBanque_(o.montant),m=normaliserTexteBanqueFiable_(o.marchand_normalise||o.libelle).replace(/\s/g,'').slice(0,60),carte=String(o.carte_fin||'');return ['HB',o.source_bancaire==='pdf'?'PDF':'FLOW',compta,achat,c,m,carte,(occurrence||1)+'/'+(total||1)].join('|');}
function assurerColonnesBancaires_(){const f=SpreadsheetApp.getActiveSpreadsheet().getSheetByName('Operations');if(!f)throw new Error('Feuille Operations introuvable.');const last=Math.max(f.getLastColumn(),1),headers=f.getRange(1,1,1,last).getValues()[0].map(x=>String(x||'').trim());const manquantes=BANKING_EXTRA_HEADERS.filter(h=>!headers.includes(h));if(manquantes.length)f.getRange(1,last+1,1,manquantes.length).setValues([manquantes]);const fin=f.getLastColumn();f.getRange(1,1,1,fin).setFontWeight('bold');return f.getRange(1,1,1,fin).getValues()[0].map(x=>String(x||'').trim());}
function lireOperationsBancaires_(){const f=SpreadsheetApp.getActiveSpreadsheet().getSheetByName('Operations'),headers=assurerColonnesBancaires_();if(f.getLastRow()<2)return[];return f.getRange(2,1,f.getLastRow()-1,headers.length).getValues().filter(r=>r.some(v=>v!==''&&v!=null)).map((r,i)=>{const o={_row:i+2};headers.forEach((h,j)=>o[h]=r[j]);return o;});}
function serialiserOpBancaire_(o,headers){return headers.map(h=>{let v=o[h];if(['date','date_comptable','date_achat','cree_le','modifie_le'].includes(h)&&v){const d=v instanceof Date?v:new Date(v);return isNaN(d)?v:d;}return v==null?'':v;});}
function enrichirDepuisCommentaireBanque_(o){const txt=String(o.commentaire||'');if(!o.libelle_bancaire){const m=txt.match(/Libellé bancaire\s*:\s*(.*?)(?:\s+\|\s+Date|\s+\[HB_MATCH:|$)/i);if(m)o.libelle_bancaire=m[1].trim();}
if(!o.date_comptable){const m=txt.match(/Date (?:comptable(?:\/débit)?|débit)\s*:\s*(\d{2})\/(\d{2})\/(\d{4})/i);if(m)o.date_comptable=new Date(Number(m[3]),Number(m[2])-1,Number(m[1]),12);}
if(!o.date_achat){const m=txt.match(/Date achat\s*:\s*(\d{2})\/(\d{2})\/(\d{4})/i);if(m)o.date_achat=new Date(Number(m[3]),Number(m[2])-1,Number(m[1]),12);}
const source=String(o.libelle_bancaire||o.commentaire||o.libelle||'');if(!o.date_achat)o.date_achat=extraireDateAchatBanque_(source)||'';if(!o.date_comptable)o.date_comptable=dateBanque_(o.date);if(!o.carte_fin)o.carte_fin=extraireCarteFinBanque_(source);if(!o.marchand_normalise)o.marchand_normalise=marchandBanque_(source,o.libelle);if(!o.source_bancaire)o.source_bancaire=/REIMPORT_PDF|RECONSTRUCTION_PDF|HELLOBANK_PDF/i.test(txt)?'pdf':(/HELLOBANK|HB_MATCH|CARTE_DIFFEREE/i.test(txt)?'flux':'manuel');if(!o.statut_bancaire)o.statut_bancaire=o.source_bancaire==='pdf'?'definitif':'provisoire';return o;}
function verifierJeuOperations_(ops){const erreurs=[],ids=new Set();let deb=0,cred=0;ops.forEach((o,i)=>{const n=i+2,id=String(o.id||'').trim(),type=String(o.type||'').toLowerCase(),mont=Number(o.montant),date=dateBanque_(o.date);if(!id)erreurs.push('Ligne '+n+' : id manquant');else if(ids.has(id))erreurs.push('Ligne '+n+' : id dupliqué '+id);else ids.add(id);if(!date)erreurs.push('Ligne '+n+' : date invalide');if(!Number.isFinite(mont)||mont===0)erreurs.push('Ligne '+n+' : montant invalide');if(!['depense','revenu'].includes(type))erreurs.push('Ligne '+n+' : type invalide');if(type==='depense'&&mont>0)erreurs.push('Ligne '+n+' : dépense positive');if(type==='revenu'&&mont<0)erreurs.push('Ligne '+n+' : revenu négatif');if(!String(o.compte||'').trim())erreurs.push('Ligne '+n+' : compte manquant');if(mont<0)deb+=Math.abs(mont);else cred+=mont;});return{ok:!erreurs.length,erreurs:erreurs.slice(0,100),nombre:ops.length,debits:Math.round(deb*100)/100,credits:Math.round(cred*100)/100,idsUniques:ids.size};}
function analyserMigrationOperations(payload){if(!payload||!Array.isArray(payload.headers)||!Array.isArray(payload.rows))throw new Error('Fichier de migration invalide.');const headers=payload.headers.map(x=>String(x||'').trim()),missing=BANKING_BASE_HEADERS.filter(h=>!headers.includes(h));if(missing.length)throw new Error('Colonnes obligatoires absentes : '+missing.join(', '));const ops=payload.rows.filter(r=>Array.isArray(r)&&r.some(v=>v!==''&&v!=null)).map(r=>{const o={};headers.forEach((h,i)=>o[h]=r[i]);return enrichirDepuisCommentaireBanque_(o);});const audit=verifierJeuOperations_(ops),actuelles=verifierJeuOperations_(lireOperationsBancaires_());return{schema:BANKING_SCHEMA_VERSION,auditNouveau:audit,auditActuel:actuelles,pret:audit.ok&&audit.nombre>0};}
function migrerOperationsControlees(payload){const lock=LockService.getDocumentLock();lock.waitLock(30000);try{const analyse=analyserMigrationOperations(payload);if(!analyse.pret)throw new Error('Migration refusée : le jeu de données ne passe pas les contrôles.');const ss=SpreadsheetApp.getActiveSpreadsheet(),f=ss.getSheetByName('Operations'),timestamp=Utilities.formatDate(new Date(),Session.getScriptTimeZone(),'yyyyMMdd_HHmmss'),backupName=('Operations_backup_'+timestamp).slice(0,99);const backup=f.copyTo(ss).setName(backupName);const headers=assurerColonnesBancaires_();const srcHeaders=payload.headers.map(x=>String(x||'').trim());const ops=payload.rows.filter(r=>Array.isArray(r)&&r.some(v=>v!==''&&v!=null)).map(r=>{const o={};srcHeaders.forEach((h,i)=>o[h]=r[i]);return enrichirDepuisCommentaireBanque_(o);});const sig={};ops.forEach(o=>{const k=[isoJourBanque_(o.date_achat||o.date),centimesBanque_(o.montant),o.marchand_normalise,o.carte_fin].join('|');sig[k]=(sig[k]||0)+1;});const seen={};ops.forEach(o=>{const k=[isoJourBanque_(o.date_achat||o.date),centimesBanque_(o.montant),o.marchand_normalise,o.carte_fin].join('|');seen[k]=(seen[k]||0)+1;if(!o.cle_rapprochement)o.cle_rapprochement=cleBanqueFiable_(o,seen[k],sig[k]);});const values=ops.map(o=>serialiserOpBancaire_(o,headers));f.clearContents();f.getRange(1,1,1,headers.length).setValues([headers]);if(values.length)f.getRange(2,1,values.length,headers.length).setValues(values);f.setFrozenRows(1);SpreadsheetApp.flush();const apres=lireOperationsBancaires_(),auditApres=verifierJeuOperations_(apres);if(!auditApres.ok||auditApres.nombre!==analyse.auditNouveau.nombre||Math.abs(auditApres.debits-analyse.auditNouveau.debits)>0.001||Math.abs(auditApres.credits-analyse.auditNouveau.credits)>0.001){f.clearContents();const bvals=backup.getDataRange().getValues();f.getRange(1,1,bvals.length,bvals[0].length).setValues(bvals);SpreadsheetApp.flush();throw new Error('Contrôle après écriture non conforme : restauration automatique effectuée.');}PropertiesService.getDocumentProperties().setProperty('BANKING_SCHEMA_VERSION',BANKING_SCHEMA_VERSION);return{ok:true,backup:backupName,audit:auditApres,colonnes:headers.length};}finally{lock.releaseLock();}}
function scoreMatchBancaire_(n,o){let s=0;if(centimesBanque_(n.montant)!==centimesBanque_(o.montant))return-999;const na=isoJourBanque_(n.date_achat||n.date),oa=isoJourBanque_(o.date_achat||o.date);if(na&&oa&&na===oa)s+=50;const nc=isoJourBanque_(n.date_comptable||n.date),oc=isoJourBanque_(o.date_comptable||o.date);if(nc&&oc&&nc===oc)s+=20;const nm=normaliserTexteBanqueFiable_(n.marchand_normalise||n.libelle),om=normaliserTexteBanqueFiable_(o.marchand_normalise||o.libelle);if(nm&&om){if(nm===om)s+=25;else if(nm.includes(om)||om.includes(nm))s+=18;else{const mots=nm.split(' ').filter(x=>x.length>3),com=mots.filter(x=>om.includes(x)).length;s+=Math.min(15,com*3);}}if(n.carte_fin&&o.carte_fin&&String(n.carte_fin)===String(o.carte_fin))s+=10;return s;}
function normaliserEntreeBancaire_(x,source){const o={source_bancaire:source,statut_bancaire:source==='pdf'?'definitif':'provisoire',date_comptable:dateBanque_(x.date_comptable||x.date),date_achat:dateBanque_(x.date_achat)||extraireDateAchatBanque_(x.libelle_bancaire||x.details||x.libelle)||'',libelle_bancaire:String(x.libelle_bancaire||x.details||x.libelle||'').trim(),libelle:String(x.libelle||'').trim(),compte:String(x.compte||'').trim(),montant:Number(x.montant),type:String(x.type||((Number(x.montant)<0)?'depense':'revenu')).toLowerCase(),marchand_normalise:String(x.marchand_normalise||'').trim(),carte_fin:String(x.carte_fin||'').trim()};if(!o.date_achat)o.date_achat=o.date_comptable;if(!o.marchand_normalise)o.marchand_normalise=marchandBanque_(o.libelle_bancaire,o.libelle);if(!o.carte_fin)o.carte_fin=extraireCarteFinBanque_(o.libelle_bancaire);o.date=o.date_achat||o.date_comptable;if(!o.libelle)o.libelle=titreLibelle? titreLibelle(o.marchand_normalise||o.libelle_bancaire):o.marchand_normalise||o.libelle_bancaire;return o;}
function upsertOperationsBancairesFiables(lignes,compte,source,meta){source=source==='pdf'?'pdf':'flux';const incoming=(lignes||[]).map(x=>normaliserEntreeBancaire_(Object.assign({},x,{compte:x.compte||compte}),source)).filter(x=>x.compte&&Number.isFinite(x.montant)&&x.date_comptable);if(!incoming.length)return{recues:0,creees:0,remplacees:0,ambigues:0,ignorees:0};const lock=LockService.getDocumentLock();lock.waitLock(30000);try{const headers=assurerColonnesBancaires_(),f=SpreadsheetApp.getActiveSpreadsheet().getSheetByName('Operations'),ops=lireOperationsBancaires_().map(enrichirDepuisCommentaireBanque_).filter(o=>String(o.compte)===String(compte));const used=new Set(),actions=[];incoming.forEach(n=>{const candidates=ops.filter(o=>!used.has(o._row)&&centimesBanque_(o.montant)===centimesBanque_(n.montant)).map(o=>({o,score:scoreMatchBancaire_(n,o)})).filter(c=>c.score>=60).sort((a,b)=>b.score-a.score);const best=candidates[0],second=candidates[1];if(best&&(!second||best.score-second.score>=8)&&best.score>=75){used.add(best.o._row);actions.push({kind:'replace',n,o:best.o,score:best.score});}else if(best){actions.push({kind:'ambiguous',n,candidates:candidates.slice(0,5)});}else actions.push({kind:'create',n});});if(source==='pdf'&&actions.some(a=>a.kind==='ambiguous'))return{recues:incoming.length,creees:actions.filter(a=>a.kind==='create').length,remplacees:actions.filter(a=>a.kind==='replace').length,ambigues:actions.filter(a=>a.kind==='ambiguous').length,ignorees:0,bloque:true,message:'Import PDF bloqué : '+actions.filter(a=>a.kind==='ambiguous').length+' rapprochement(s) ambigu(s).'};let created=0,replaced=0;actions.forEach(a=>{if(a.kind==='ambiguous')return;if(a.kind==='replace'){const old=a.o,n=a.n;const out=Object.assign({},old,{date:n.date,date_comptable:n.date_comptable,date_achat:n.date_achat,libelle:n.libelle||old.libelle,libelle_bancaire:n.libelle_bancaire,marchand_normalise:n.marchand_normalise,carte_fin:n.carte_fin,source_bancaire:n.source_bancaire,statut_bancaire:n.statut_bancaire,modifie_le:new Date()});if(source!=='pdf'&&String(old.statut_bancaire)==='definitif')return;out.cle_rapprochement=cleBanqueFiable_(out,1,1);f.getRange(old._row,1,1,headers.length).setValues([serialiserOpBancaire_(out,headers)]);replaced++;}else{const n=a.n,id=Utilities.getUuid(),now=new Date();const out=Object.assign({id,categorie:'',commentaire:'',cree_le:now,modifie_le:now},n);out.cle_rapprochement=cleBanqueFiable_(out,1,1);f.appendRow(serialiserOpBancaire_(out,headers));created++;}});return{recues:incoming.length,creees:created,remplacees:replaced,ambigues:actions.filter(a=>a.kind==='ambiguous').length,ignorees:actions.filter(a=>a.kind==='ambiguous').length,bloque:false};}finally{lock.releaseLock();}}
function etatIntegriteBancaire(){const ops=lireOperationsBancaires_().map(enrichirDepuisCommentaireBanque_),audit=verifierJeuOperations_(ops),def=ops.filter(o=>o.statut_bancaire==='definitif').length,prov=ops.filter(o=>o.statut_bancaire==='provisoire').length,cles=ops.filter(o=>String(o.cle_rapprochement||'').trim()).length;return{schema:BANKING_SCHEMA_VERSION,audit,definitives:def,provisoires:prov,clesRapprochement:cles,total:ops.length};}
