const BULK_RULES_SHEET='Regles_categories';
const BULK_RULES_HEADERS=['id','motif','categorie','type','actif','cree_le','modifie_le'];
function initialiserReglesCategories_(){const ss=SpreadsheetApp.getActiveSpreadsheet();let f=ss.getSheetByName(BULK_RULES_SHEET);if(!f)f=ss.insertSheet(BULK_RULES_SHEET);if(f.getLastRow()===0)f.getRange(1,1,1,BULK_RULES_HEADERS.length).setValues([BULK_RULES_HEADERS]);f.setFrozenRows(1);return f;}
function lireReglesCategories(){const f=initialiserReglesCategories_();if(f.getLastRow()<2)return[];return f.getRange(2,1,f.getLastRow()-1,BULK_RULES_HEADERS.length).getValues().map(r=>Object.fromEntries(BULK_RULES_HEADERS.map((h,i)=>[h,r[i] instanceof Date?r[i].toISOString():r[i]]))).filter(x=>String(x.actif).toLowerCase()!=='false');}
function texteOperationRegle_(o){return normaliserTexteBanque_([o.marchand_normalise||'',o.libelle_bancaire||'',o.libelle||'',o.commentaire||''].join(' '));}
function indexTypesCategoriesRegle_(){const index=new Map();lireTable_('Categories').forEach(c=>{const nom=String(c.nom||'').trim();if(nom)index.set(nom,String(c.type||'').toLowerCase());});return index;}
function typeCategorieOperationRegle_(o,indexCategories){const categorie=String(o.categorie||'').trim();if(categorie&&indexCategories&&indexCategories.get(categorie)==='tresorerie')return'tresorerie';const t=String(o.type||'').toLowerCase();if(t==='depense'||t==='revenu')return t;const m=Number(o.montant||0);if(Number.isFinite(m)&&m!==0)return m<0?'depense':'revenu';return'';}
function trouverMatchesRegleCategorie_(payload){const motifs=String(payload?.motifs||'').split(/[\n,;]+/).map(x=>normaliserTexteBanque_(x)).filter(x=>x.length>=2);if(!motifs.length)throw new Error('Saisissez au moins un libellé ou mot-clé.');return lireTable_('Operations').filter(o=>!String(o.commentaire||'').includes('[RECURRENCE:')&&motifs.some(m=>texteOperationRegle_(o).includes(m)));}
function analyserRegleCategorie(payload){const categorie=String(payload?.categorie||'').trim(),typeCible=String(payload?.type||'depense').toLowerCase(),matches=trouverMatchesRegleCategorie_(payload),indexCategories=indexTypesCategoriesRegle_();const sans=matches.filter(o=>!String(o.categorie||'').trim()).length,meme=matches.filter(o=>categorie&&String(o.categorie||'').trim()===categorie).length,autre=matches.filter(o=>String(o.categorie||'').trim()&&(!categorie||String(o.categorie||'').trim()!==categorie)).length;return{total:matches.length,sansCategorie:sans,dejaBonneCategorie:meme,categorieDifferente:autre,dejaCategoriees:matches.length-sans,resultats:matches.map(o=>{const typeDetecte=typeCategorieOperationRegle_(o,indexCategories);return{id:o.id,date:o.date,libelle:o.libelle,categorie:o.categorie||'',montant:o.montant,compte:o.compte||'',marchand_normalise:o.marchand_normalise||'',libelle_bancaire:o.libelle_bancaire||'',typeDetecte,typeCompatible:typeDetecte===typeCible};})};}
function motifsApprentissageSelection_(ops){const motifs=[];ops.forEach(o=>{let m=normaliserTexteBanque_(o.marchand_normalise||'');if(!m)m=extraireMotifStableBanque_(o.libelle_bancaire||o.libelle||'');if(m&&m.length>=3)motifs.push(m);});return [...new Set(motifs)];}
function appliquerRegleCategorie(payload){verifierInitialisation_();const categorie=String(payload?.categorie||'').trim(),type=String(payload?.type||'depense').toLowerCase(),motifsBruts=String(payload?.motifs||'').split(/[\n,;]+/).map(x=>x.trim()).filter(Boolean),ecraser=payload?.ecraser!==false&&String(payload?.ecraser)!=='false';if(!categorie)throw new Error('Choisissez une catégorie.');if(!motifsBruts.length)throw new Error('Saisissez au moins un libellé ou mot-clé.');const matches=trouverMatchesRegleCategorie_(payload),selectionExplicite=Array.isArray(payload?.idsSelectionnes),ids=new Set((payload?.idsSelectionnes||[]).map(String));if(selectionExplicite&&!ids.size)throw new Error('Aucune opération sélectionnée.');const cible=selectionExplicite?matches.filter(o=>ids.has(String(o.id))):matches;let modifiees=0,ignorees=0,dejaCorrectes=0;cible.forEach(o=>{const actuelle=String(o.categorie||'').trim();if(actuelle===categorie){dejaCorrectes++;return;}if(actuelle&&!ecraser){ignorees++;return;}enregistrerLigne('Operations',Object.assign({},o,{categorie,montant:Math.abs(Number(o.montant||0))}));modifiees++;});const f=initialiserReglesCategories_(),now=new Date().toISOString(),selectionPartielle=selectionExplicite&&cible.length<matches.length;let motifsAppris=motifsBruts;if(selectionPartielle)motifsAppris=motifsApprentissageSelection_(cible);motifsAppris.forEach(m=>f.appendRow([Utilities.getUuid(),m,categorie,type,true,now,now]));return{trouvees:matches.length,selectionnees:cible.length,modifiees,ignorees,dejaCorrectes,categorie,selectionPartielle,motifsAppris:motifsAppris.length};}
