const CATEGORY_INTELLIGENCE_VERSION='1.1';

function normaliserCategorieIntelligente_(v){return String(v||'').trim();}
function indexCategoriesIntelligentes_(){const cats=lireTable_('Categories').filter(c=>String(c.actif).toLowerCase()!=='false');const map=new Map();cats.forEach(c=>map.set(normaliserTexteBanque_(c.nom),{nom:String(c.nom||'').trim(),type:String(c.type||'').toLowerCase()}));return map;}
function typeOperationCategorie_(o,categorie,index){const c=index.get(normaliserTexteBanque_(categorie));if(c&&c.type)return c.type;return Number(o.montant||0)<0?'depense':'revenu';}
function texteCategorieIntelligente_(o){return normaliserTexteBanque_([o.marchand_normalise||'',o.libelle_bancaire||'',o.libelle||''].join(' '));}
function propositionCategorieOperation_(o,correspondances,regles,indexCats){const texte=texteCategorieIntelligente_(o),compte=String(o.compte||''),candidats=[];
  (correspondances||[]).forEach(c=>{if(c.actif===false||String(c.actif).toLowerCase()==='false')return;if(c.compte&&String(c.compte)!==compte)return;const motif=normaliserTexteBanque_(c.motif_bancaire);const cat=normaliserCategorieIntelligente_(c.categorie);if(!motif||!cat||!texte.includes(motif)||!indexCats.has(normaliserTexteBanque_(cat)))return;candidats.push({categorie:cat,type:typeOperationCategorie_(o,cat,indexCats),score:100+Math.min(30,motif.length),source:'correspondance',motif,correspondanceId:c.id||''});});
  (regles||[]).forEach(r=>{if(String(r.actif).toLowerCase()==='false')return;const motif=normaliserTexteBanque_(r.motif),cat=normaliserCategorieIntelligente_(r.categorie);if(!motif||!cat||!texte.includes(motif)||!indexCats.has(normaliserTexteBanque_(cat)))return;candidats.push({categorie:cat,type:typeOperationCategorie_(o,cat,indexCats),score:70+Math.min(25,motif.length),source:'regle',motif,regleId:r.id||''});});
  candidats.sort((a,b)=>b.score-a.score||b.motif.length-a.motif.length);if(!candidats.length)return null;const best=candidats[0],conflit=candidats.find(c=>c.categorie!==best.categorie&&c.score>=best.score-5);if(conflit)return{statut:'ambigu',best,conflit};return{statut:'propose',best};}
function cleGroupeCategorie_(o,p){return [p.best.source,p.best.motif,String(o.compte||''),p.best.categorie].join('|');}
function operationCorrespondAuGroupe_(o,groupe){const texte=texteCategorieIntelligente_(o);return texte.includes(normaliserTexteBanque_(groupe.motif))&&(!groupe.compte||String(o.compte||'')===String(groupe.compte));}
function sauvegarderCategorieOperationSansAltererBanque_(o,categorie){if(String(o.categorie||'').trim()===String(categorie||'').trim())return false;enregistrerLigne('Operations',Object.assign({},o,{categorie:String(categorie||'').trim(),montant:Math.abs(Number(o.montant||0))}));return true;}

function simulerCategorisationIntelligenteBudgetSoft(){verifierInitialisation_();const ops=lireTable_('Operations'),corr=typeof lireCorrespondancesBancaires==='function'?lireCorrespondancesBancaires():[],regles=typeof lireReglesCategories==='function'?lireReglesCategories():[],index=indexCategoriesIntelligentes_();let sansCategorie=0,proposees=0,dejaCorrectes=0,changements=0,ambigues=0,sansProposition=0;const exemples=[];ops.forEach(o=>{const actuelle=normaliserCategorieIntelligente_(o.categorie);if(!actuelle)sansCategorie++;const p=propositionCategorieOperation_(o,corr,regles,index);if(!p){sansProposition++;return;}if(p.statut==='ambigu'){ambigues++;if(exemples.length<100)exemples.push({id:o.id,date:o.date,libelle:o.libelle,marchand:o.marchand_normalise||'',categorieActuelle:actuelle,statut:'ambigu',proposition:p.best.categorie,alternative:p.conflit.categorie,source:p.best.source});return;}proposees++;if(actuelle===p.best.categorie)dejaCorrectes++;else changements++;if(exemples.length<100&&(actuelle!==p.best.categorie||!actuelle))exemples.push({id:o.id,date:o.date,libelle:o.libelle,marchand:o.marchand_normalise||'',categorieActuelle:actuelle,statut:'propose',proposition:p.best.categorie,typePropose:p.best.type,source:p.best.source,motif:p.best.motif,score:p.best.score});});const resume={version:CATEGORY_INTELLIGENCE_VERSION,totalOperations:ops.length,sansCategorie,proposees,dejaCorrectes,changementsPotentiels:changements,ambigues,sansProposition,aucuneEcriture:true,exemples};console.log(JSON.stringify(resume));return resume;}

function listerGroupesCategorisationBudgetSoft(){verifierInitialisation_();const ops=lireTable_('Operations'),corr=lireCorrespondancesBancaires(),regles=lireReglesCategories(),index=indexCategoriesIntelligentes_(),groupes=new Map();ops.forEach(o=>{const p=propositionCategorieOperation_(o,corr,regles,index);if(!p||p.statut!=='propose')return;const actuelle=normaliserCategorieIntelligente_(o.categorie);if(actuelle===p.best.categorie)return;const key=cleGroupeCategorie_(o,p);if(!groupes.has(key))groupes.set(key,{cle:key,motif:p.best.motif,compte:String(o.compte||''),proposition:p.best.categorie,source:p.best.source,score:p.best.score,nombre:0,sansCategorie:0,categoriesActuelles:{},exemples:[]});const g=groupes.get(key);g.nombre++;if(!actuelle)g.sansCategorie++;else g.categoriesActuelles[actuelle]=(g.categoriesActuelles[actuelle]||0)+1;if(g.exemples.length<5)g.exemples.push({id:o.id,date:o.date,libelle:o.libelle,marchand:o.marchand_normalise||'',montant:o.montant,categorieActuelle:actuelle});});const categories=lireTable_('Categories').filter(c=>String(c.actif).toLowerCase()!=='false').map(c=>({nom:c.nom,type:c.type})).sort((a,b)=>String(a.type).localeCompare(String(b.type))||String(a.nom).localeCompare(String(b.nom)));return{version:CATEGORY_INTELLIGENCE_VERSION,totalOperations:ops.length,nombreGroupes:groupes.size,groupes:Array.from(groupes.values()).sort((a,b)=>b.nombre-a.nombre||b.score-a.score),categories};}

function appliquerCategorieAuGroupe_(groupe,categorie){const ops=lireTable_('Operations');let trouvees=0,modifiees=0,deja=0;ops.forEach(o=>{if(!operationCorrespondAuGroupe_(o,groupe))return;trouvees++;if(String(o.categorie||'').trim()===categorie){deja++;return;}if(sauvegarderCategorieOperationSansAltererBanque_(o,categorie))modifiees++;});return{trouvees,modifiees,deja};}
function validerGroupeCategorisationBudgetSoft(groupe){verifierInitialisation_();const motif=normaliserTexteBanque_(groupe?.motif),categorie=String(groupe?.proposition||'').trim(),compte=String(groupe?.compte||'');if(!motif||!categorie)throw new Error('Groupe ou catégorie manquant.');const index=indexCategoriesIntelligentes_();if(!index.has(normaliserTexteBanque_(categorie)))throw new Error('Catégorie inconnue : '+categorie);const resultat=appliquerCategorieAuGroupe_({motif,compte},categorie);return Object.assign({ok:true,motif,categorie},resultat);}
function contreProposerGroupeCategorisationBudgetSoft(groupe,nouvelleCategorie){verifierInitialisation_();const motif=normaliserTexteBanque_(groupe?.motif),compte=String(groupe?.compte||''),categorie=String(nouvelleCategorie||'').trim();if(!motif||!categorie)throw new Error('Motif ou catégorie manquant.');const index=indexCategoriesIntelligentes_(),cat=index.get(normaliserTexteBanque_(categorie));if(!cat)throw new Error('Catégorie inconnue : '+categorie);const correspondances=lireCorrespondancesBancaires();let c=correspondances.find(x=>normaliserTexteBanque_(x.motif_bancaire)===motif&&String(x.compte||'')===compte);if(!c)c=correspondances.find(x=>normaliserTexteBanque_(x.motif_bancaire)===motif&&!x.compte);if(c){c.categorie=categorie;c.type=cat.type==='tresorerie'?'':cat.type;c.actif=true;enregistrerCorrespondanceBancaire(c);}else{enregistrerCorrespondanceBancaire({motif_bancaire:motif,libelle_normalise:String(groupe?.libelleNormalise||motif),categorie,type:cat.type==='tresorerie'?'':cat.type,compte,actif:true,utilisations:1});}const resultat=appliquerCategorieAuGroupe_({motif,compte},categorie);return Object.assign({ok:true,motif,categorie,apprentissage:true},resultat);}

function appliquerCategorisationIntelligenteBudgetSoft(options){verifierInitialisation_();options=options||{};const seulementVides=options.seulementVides!==false&&String(options.seulementVides)!=='false',corr=lireCorrespondancesBancaires(),regles=lireReglesCategories(),index=indexCategoriesIntelligentes_(),ops=lireTable_('Operations');let modifiees=0,ignorees=0,ambigues=0;ops.forEach(o=>{const actuelle=normaliserCategorieIntelligente_(o.categorie);if(seulementVides&&actuelle){ignorees++;return;}const p=propositionCategorieOperation_(o,corr,regles,index);if(!p){ignorees++;return;}if(p.statut==='ambigu'){ambigues++;return;}if(actuelle===p.best.categorie){ignorees++;return;}if(sauvegarderCategorieOperationSansAltererBanque_(o,p.best.categorie))modifiees++;});return{modifiees,ignorees,ambigues,seulementVides};}
