const CATEGORY_INTELLIGENCE_VERSION='1.0';

function normaliserCategorieIntelligente_(v){return String(v||'').trim();}
function indexCategoriesIntelligentes_(){const cats=lireTable_('Categories').filter(c=>String(c.actif).toLowerCase()!=='false');const map=new Map();cats.forEach(c=>map.set(normaliserTexteBanque_(c.nom),{nom:String(c.nom||'').trim(),type:String(c.type||'').toLowerCase()}));return map;}
function typeOperationCategorie_(o,categorie,index){const c=index.get(normaliserTexteBanque_(categorie));if(c&&c.type)return c.type;return Number(o.montant||0)<0?'depense':'revenu';}
function texteCategorieIntelligente_(o){return normaliserTexteBanque_([o.marchand_normalise||'',o.libelle_bancaire||'',o.libelle||''].join(' '));}
function propositionCategorieOperation_(o,correspondances,regles,indexCats){const texte=texteCategorieIntelligente_(o),compte=String(o.compte||''),candidats=[];
  (correspondances||[]).forEach(c=>{if(c.actif===false||String(c.actif).toLowerCase()==='false')return;if(c.compte&&String(c.compte)!==compte)return;const motif=normaliserTexteBanque_(c.motif_bancaire);const cat=normaliserCategorieIntelligente_(c.categorie);if(!motif||!cat||!texte.includes(motif)||!indexCats.has(normaliserTexteBanque_(cat)))return;candidats.push({categorie:cat,type:typeOperationCategorie_(o,cat,indexCats),score:100+Math.min(30,motif.length),source:'correspondance',motif});});
  (regles||[]).forEach(r=>{if(String(r.actif).toLowerCase()==='false')return;const motif=normaliserTexteBanque_(r.motif),cat=normaliserCategorieIntelligente_(r.categorie);if(!motif||!cat||!texte.includes(motif)||!indexCats.has(normaliserTexteBanque_(cat)))return;candidats.push({categorie:cat,type:typeOperationCategorie_(o,cat,indexCats),score:70+Math.min(25,motif.length),source:'regle',motif});});
  candidats.sort((a,b)=>b.score-a.score||b.motif.length-a.motif.length);if(!candidats.length)return null;const best=candidats[0],conflit=candidats.find(c=>c.categorie!==best.categorie&&c.score>=best.score-5);if(conflit)return{statut:'ambigu',best,conflit};return{statut:'propose',best};}

function simulerCategorisationIntelligenteBudgetSoft(){verifierInitialisation_();const ops=lireTable_('Operations'),corr=typeof lireCorrespondancesBancaires==='function'?lireCorrespondancesBancaires():[],regles=typeof lireReglesCategories==='function'?lireReglesCategories():[],index=indexCategoriesIntelligentes_();let sansCategorie=0,proposees=0,dejaCorrectes=0,changements=0,ambigues=0,sansProposition=0;const exemples=[];ops.forEach(o=>{const actuelle=normaliserCategorieIntelligente_(o.categorie);if(!actuelle)sansCategorie++;const p=propositionCategorieOperation_(o,corr,regles,index);if(!p){sansProposition++;return;}if(p.statut==='ambigu'){ambigues++;if(exemples.length<100)exemples.push({id:o.id,date:o.date,libelle:o.libelle,marchand:o.marchand_normalise||'',categorieActuelle:actuelle,statut:'ambigu',proposition:p.best.categorie,alternative:p.conflit.categorie,source:p.best.source});return;}proposees++;if(actuelle===p.best.categorie)dejaCorrectes++;else changements++;if(exemples.length<100&&(actuelle!==p.best.categorie||!actuelle))exemples.push({id:o.id,date:o.date,libelle:o.libelle,marchand:o.marchand_normalise||'',categorieActuelle:actuelle,statut:'propose',proposition:p.best.categorie,typePropose:p.best.type,source:p.best.source,motif:p.best.motif,score:p.best.score});});return{version:CATEGORY_INTELLIGENCE_VERSION,totalOperations:ops.length,sansCategorie,proposees,dejaCorrectes,changementsPotentiels:changements,ambigues,sansProposition,aucuneEcriture:true,exemples};}

function appliquerCategorisationIntelligenteBudgetSoft(options){verifierInitialisation_();options=options||{};const seulementVides=options.seulementVides!==false&&String(options.seulementVides)!=='false',corr=lireCorrespondancesBancaires(),regles=lireReglesCategories(),index=indexCategoriesIntelligentes_(),ops=lireTable_('Operations');let modifiees=0,ignorees=0,ambigues=0;ops.forEach(o=>{const actuelle=normaliserCategorieIntelligente_(o.categorie);if(seulementVides&&actuelle){ignorees++;return;}const p=propositionCategorieOperation_(o,corr,regles,index);if(!p){ignorees++;return;}if(p.statut==='ambigu'){ambigues++;return;}if(actuelle===p.best.categorie){ignorees++;return;}enregistrerLigne('Operations',Object.assign({},o,{categorie:p.best.categorie,type:p.best.type,montant:Math.abs(Number(o.montant||0))}));modifiees++;});return{modifiees,ignorees,ambigues,seulementVides};}
