const CATEGORY_INTELLIGENCE_VERSION='1.4';

function normaliserCategorieIntelligente_(v){return String(v||'').trim();}
function indexCategoriesIntelligentes_(){const cats=lireTable_('Categories').filter(c=>String(c.actif).toLowerCase()!=='false');const map=new Map();cats.forEach(c=>map.set(normaliserTexteBanque_(c.nom),{nom:String(c.nom||'').trim(),type:String(c.type||'').toLowerCase()}));return map;}
function typeOperationReelCategorie_(o){const t=String(o&&o.type||'').toLowerCase();if(t==='depense'||t==='revenu'||t==='tresorerie')return t;const m=Number(o&&o.montant||0);return Number.isFinite(m)&&m<0?'depense':'revenu';}
function typeOperationCategorie_(o,categorie,index){const c=index.get(normaliserTexteBanque_(categorie));if(c&&c.type)return c.type;return typeOperationReelCategorie_(o);}
function categorieCompatibleOperation_(o,categorie,index){const c=index.get(normaliserTexteBanque_(categorie));if(!c||!c.type)return false;const opType=typeOperationReelCategorie_(o);if(c.type==='tresorerie')return true;if(c.type==='epargne')return opType==='depense'||opType==='revenu';return c.type===opType;}
function sourceCompatibleOperation_(o,typeSource){const t=String(typeSource||'').toLowerCase();if(!t)return true;if(t==='tresorerie'||t==='epargne')return true;return t===typeOperationReelCategorie_(o);}
function texteCategorieIntelligente_(o){return normaliserTexteBanque_([o.marchand_normalise||'',o.libelle_bancaire||'',o.libelle||''].join(' '));}
function motifHistoriqueOperation_(o){const marchand=normaliserTexteBanque_(o.marchand_normalise||'');if(marchand&&marchand.length>=3)return marchand;const brut=normaliserTexteBanque_(o.libelle_bancaire||o.libelle||'').replace(/\b\d{2,}\b/g,' ').replace(/\b(PRLV|SEPA|VIR|VIREMENT|CARTE|PAIEMENT|CB|RETRAIT|DAB|RECU|INSTANT|EMIS|DEBIT|CREDIT)\b/g,' ').replace(/\s+/g,' ').trim();return brut.split(' ').filter(x=>x.length>2).slice(0,5).join(' ');}
function construireHistoriqueCategories_(ops,indexCats){const stats=new Map();(ops||[]).forEach(o=>{const cat=normaliserCategorieIntelligente_(o.categorie);if(!cat||!indexCats.has(normaliserTexteBanque_(cat))||!categorieCompatibleOperation_(o,cat,indexCats))return;const motif=motifHistoriqueOperation_(o);if(!motif||motif.length<3)return;if(!stats.has(motif))stats.set(motif,{total:0,categories:{}});const s=stats.get(motif);s.total++;s.categories[cat]=(s.categories[cat]||0)+1;});const hist=new Map();stats.forEach((s,motif)=>{const tri=Object.entries(s.categories).sort((a,b)=>b[1]-a[1]);if(!tri.length)return;const [cat,n]=tri[0],taux=n/s.total;if(n>=2&&taux>=0.8)hist.set(motif,{categorie:cat,total:s.total,occurrences:n,taux});});return hist;}
function estTicketTisseoAnonyme_(o,texte){const m=Math.abs(Number(o&&o.montant||0));if(typeOperationReelCategorie_(o)!=='depense'||Math.abs(m-1.80)>0.001)return false;const t=String(texte||'');return /(?:^|\s)TI(?:\s|$)/.test(t);}
function propositionCategorieOperation_(o,correspondances,regles,indexCats,historique){const texte=texteCategorieIntelligente_(o),compte=String(o.compte||''),candidats=[];
  if(estTicketTisseoAnonyme_(o,texte)&&indexCats.has(normaliserTexteBanque_('Transports')))candidats.push({categorie:'Transports',type:'depense',score:118,source:'heuristique_transport',motif:'TI + 1,80 EUR'});
  (correspondances||[]).forEach(c=>{if(c.actif===false||String(c.actif).toLowerCase()==='false')return;if(c.compte&&String(c.compte)!==compte)return;const motif=normaliserTexteBanque_(c.motif_bancaire),cat=normaliserCategorieIntelligente_(c.categorie);if(!motif||!cat||!texte.includes(motif)||!indexCats.has(normaliserTexteBanque_(cat)))return;if(!sourceCompatibleOperation_(o,c.type)||!categorieCompatibleOperation_(o,cat,indexCats))return;candidats.push({categorie:cat,type:typeOperationCategorie_(o,cat,indexCats),score:110+Math.min(30,motif.length),source:'correspondance',motif,correspondanceId:c.id||''});});
  (regles||[]).forEach(r=>{if(String(r.actif).toLowerCase()==='false')return;const motif=normaliserTexteBanque_(r.motif),cat=normaliserCategorieIntelligente_(r.categorie);if(!motif||!cat||!texte.includes(motif)||!indexCats.has(normaliserTexteBanque_(cat)))return;if(!sourceCompatibleOperation_(o,r.type)||!categorieCompatibleOperation_(o,cat,indexCats))return;candidats.push({categorie:cat,type:typeOperationCategorie_(o,cat,indexCats),score:70+Math.min(25,motif.length),source:'regle',motif,regleId:r.id||''});});
  const mh=motifHistoriqueOperation_(o),h=historique&&historique.get(mh);if(h&&indexCats.has(normaliserTexteBanque_(h.categorie))&&categorieCompatibleOperation_(o,h.categorie,indexCats)){candidats.push({categorie:h.categorie,type:typeOperationCategorie_(o,h.categorie,indexCats),score:85+Math.min(10,h.occurrences),source:'historique',motif:mh,occurrences:h.occurrences,taux:h.taux});}
  candidats.sort((a,b)=>b.score-a.score||String(b.motif||'').length-String(a.motif||'').length);if(!candidats.length)return null;const best=candidats[0],conflit=candidats.find(c=>c.categorie!==best.categorie&&c.score>=best.score-5);if(conflit)return{statut:'ambigu',best,conflit};return{statut:'propose',best};}
function cleGroupeCategorie_(o,p){return [p.best.source,p.best.motif,String(o.compte||''),p.best.categorie].join('|');}
function operationCorrespondAuGroupe_(o,groupe){if(groupe.source==='historique')return motifHistoriqueOperation_(o)===String(groupe.motif||'');if(groupe.source==='heuristique_transport')return estTicketTisseoAnonyme_(o,texteCategorieIntelligente_(o));const texte=texteCategorieIntelligente_(o);return texte.includes(normaliserTexteBanque_(groupe.motif))&&(!groupe.compte||String(o.compte||'')===String(groupe.compte));}
function sauvegarderCategorieOperationSansAltererBanque_(o,categorie){if(String(o.categorie||'').trim()===String(categorie||'').trim())return false;enregistrerLigne('Operations',Object.assign({},o,{categorie:String(categorie||'').trim(),montant:Math.abs(Number(o.montant||0))}));return true;}

function simulerCategorisationIntelligenteBudgetSoft(){verifierInitialisation_();const ops=lireTable_('Operations'),corr=typeof lireCorrespondancesBancaires==='function'?lireCorrespondancesBancaires():[],regles=typeof lireReglesCategories==='function'?lireReglesCategories():[],index=indexCategoriesIntelligentes_(),historique=construireHistoriqueCategories_(ops,index);let sansCategorie=0,proposees=0,dejaCorrectes=0,changements=0,ambigues=0,sansProposition=0,incompatiblesExistantes=0;const exemples=[];ops.forEach(o=>{const actuelle=normaliserCategorieIntelligente_(o.categorie);if(!actuelle)sansCategorie++;else if(index.has(normaliserTexteBanque_(actuelle))&&!categorieCompatibleOperation_(o,actuelle,index))incompatiblesExistantes++;const p=propositionCategorieOperation_(o,corr,regles,index,historique);if(!p){sansProposition++;return;}if(p.statut==='ambigu'){ambigues++;if(exemples.length<100)exemples.push({id:o.id,date:o.date,libelle:o.libelle,marchand:o.marchand_normalise||'',categorieActuelle:actuelle,statut:'ambigu',proposition:p.best.categorie,alternative:p.conflit.categorie,source:p.best.source});return;}proposees++;if(actuelle===p.best.categorie)dejaCorrectes++;else changements++;if(exemples.length<100&&(actuelle!==p.best.categorie||!actuelle))exemples.push({id:o.id,date:o.date,libelle:o.libelle,marchand:o.marchand_normalise||'',categorieActuelle:actuelle,statut:'propose',proposition:p.best.categorie,typePropose:p.best.type,source:p.best.source,motif:p.best.motif,score:p.best.score});});const resume={version:CATEGORY_INTELLIGENCE_VERSION,totalOperations:ops.length,sansCategorie,incompatiblesExistantes,proposees,dejaCorrectes,changementsPotentiels:changements,ambigues,sansProposition,groupesHistorique:historique.size,aucuneEcriture:true,exemples};console.log(JSON.stringify(resume));return resume;}

function listerGroupesCategorisationBudgetSoft(){verifierInitialisation_();const ops=lireTable_('Operations'),corr=lireCorrespondancesBancaires(),regles=lireReglesCategories(),index=indexCategoriesIntelligentes_(),historique=construireHistoriqueCategories_(ops,index),groupes=new Map();ops.forEach(o=>{const p=propositionCategorieOperation_(o,corr,regles,index,historique);if(!p||p.statut!=='propose')return;const actuelle=normaliserCategorieIntelligente_(o.categorie);if(actuelle===p.best.categorie)return;const key=cleGroupeCategorie_(o,p);if(!groupes.has(key))groupes.set(key,{cle:key,motif:p.best.motif,compte:String(o.compte||''),proposition:p.best.categorie,source:p.best.source,score:p.best.score,nombre:0,sansCategorie:0,categoriesActuelles:{},exemples:[]});const g=groupes.get(key);g.nombre++;if(!actuelle)g.sansCategorie++;else g.categoriesActuelles[actuelle]=(g.categoriesActuelles[actuelle]||0)+1;if(g.exemples.length<5)g.exemples.push({id:o.id,date:o.date,libelle:o.libelle,marchand:o.marchand_normalise||'',montant:o.montant,categorieActuelle:actuelle});});const categories=lireTable_('Categories').filter(c=>String(c.actif).toLowerCase()!=='false').map(c=>({nom:c.nom,type:c.type})).sort((a,b)=>String(a.type).localeCompare(String(b.type))||String(a.nom).localeCompare(String(b.nom)));return{version:CATEGORY_INTELLIGENCE_VERSION,totalOperations:ops.length,nombreGroupes:groupes.size,groupesHistorique:Array.from(groupes.values()).filter(g=>g.source==='historique').length,groupes:Array.from(groupes.values()).sort((a,b)=>b.nombre-a.nombre||b.score-a.score),categories};}

function appliquerCategorieAuGroupe_(groupe,categorie){const ops=lireTable_('Operations'),index=indexCategoriesIntelligentes_();let trouvees=0,modifiees=0,deja=0,incompatibles=0;ops.forEach(o=>{if(!operationCorrespondAuGroupe_(o,groupe))return;trouvees++;if(!categorieCompatibleOperation_(o,categorie,index)){incompatibles++;return;}if(String(o.categorie||'').trim()===categorie){deja++;return;}if(sauvegarderCategorieOperationSansAltererBanque_(o,categorie))modifiees++;});return{trouvees,modifiees,deja,incompatibles};}
function validerGroupeCategorisationBudgetSoft(groupe){verifierInitialisation_();const motif=String(groupe?.motif||'').trim(),categorie=String(groupe?.proposition||'').trim(),compte=String(groupe?.compte||''),source=String(groupe?.source||'');if(!motif||!categorie)throw new Error('Groupe ou catégorie manquant.');const index=indexCategoriesIntelligentes_();if(!index.has(normaliserTexteBanque_(categorie)))throw new Error('Catégorie inconnue : '+categorie);const resultat=appliquerCategorieAuGroupe_({motif,compte,source},categorie);return Object.assign({ok:true,motif,categorie},resultat);}
function contreProposerGroupeCategorisationBudgetSoft(groupe,nouvelleCategorie){verifierInitialisation_();const motif=String(groupe?.motif||'').trim(),compte=String(groupe?.compte||''),source=String(groupe?.source||''),categorie=String(nouvelleCategorie||'').trim();if(!motif||!categorie)throw new Error('Motif ou catégorie manquant.');const index=indexCategoriesIntelligentes_(),cat=index.get(normaliserTexteBanque_(categorie));if(!cat)throw new Error('Catégorie inconnue : '+categorie);const motifAppris=normaliserTexteBanque_(motif),correspondances=lireCorrespondancesBancaires();let c=correspondances.find(x=>normaliserTexteBanque_(x.motif_bancaire)===motifAppris&&String(x.compte||'')===compte);if(!c)c=correspondances.find(x=>normaliserTexteBanque_(x.motif_bancaire)===motifAppris&&!x.compte);if(c){c.categorie=categorie;c.type=cat.type==='tresorerie'?'tresorerie':cat.type;c.actif=true;enregistrerCorrespondanceBancaire(c);}else{enregistrerCorrespondanceBancaire({motif_bancaire:motifAppris,libelle_normalise:String(groupe?.libelleNormalise||motif),categorie,type:cat.type,compte,actif:true,utilisations:1});}const resultat=appliquerCategorieAuGroupe_({motif,compte,source},categorie);return Object.assign({ok:true,motif,categorie,apprentissage:true},resultat);}

function appliquerCategorisationIntelligenteBudgetSoft(options){verifierInitialisation_();options=options||{};const seulementVides=options.seulementVides!==false&&String(options.seulementVides)!=='false',corr=lireCorrespondancesBancaires(),regles=lireReglesCategories(),index=indexCategoriesIntelligentes_(),ops=lireTable_('Operations'),historique=construireHistoriqueCategories_(ops,index);let modifiees=0,ignorees=0,ambigues=0;ops.forEach(o=>{const actuelle=normaliserCategorieIntelligente_(o.categorie);if(seulementVides&&actuelle){ignorees++;return;}const p=propositionCategorieOperation_(o,corr,regles,index,historique);if(!p){ignorees++;return;}if(p.statut==='ambigu'){ambigues++;return;}if(actuelle===p.best.categorie){ignorees++;return;}if(sauvegarderCategorieOperationSansAltererBanque_(o,p.best.categorie))modifiees++;});return{modifiees,ignorees,ambigues,seulementVides};}
