const CERBERE_CONSOLIDATION_VERSION='1.0.8';

function invaliderProjectionBudgetSoft_(origine){const props=PropertiesService.getDocumentProperties(),maintenant=new Date().toISOString();props.setProperty('BUDGETSOFT_PROJECTION_DIRTY','true');props.setProperty('BUDGETSOFT_PROJECTION_DIRTY_LE',maintenant);props.setProperty('BUDGETSOFT_PROJECTION_DIRTY_ORIGINE',String(origine||'inconnue'));props.setProperty('PLAN_DERNIER_RECALCUL',maintenant);props.setProperty('PLAN_DERNIERE_ORIGINE',String(origine||'inconnue'));return{ok:true,invalidee:true,origine:String(origine||'inconnue'),date:maintenant};}
function marquerProjectionBudgetSoftCalculee_(version){const props=PropertiesService.getDocumentProperties();props.setProperty('BUDGETSOFT_PROJECTION_DIRTY','false');props.setProperty('CERBERE_DERNIER_RECALCUL',new Date().toISOString());props.setProperty('CERBERE_DERNIERE_VERSION',String(version||''));}
function etatProjectionBudgetSoft(){const p=PropertiesService.getDocumentProperties();return{dirty:p.getProperty('BUDGETSOFT_PROJECTION_DIRTY')==='true',dirty_le:p.getProperty('BUDGETSOFT_PROJECTION_DIRTY_LE')||'',origine:p.getProperty('BUDGETSOFT_PROJECTION_DIRTY_ORIGINE')||'',dernier_calcul:p.getProperty('CERBERE_DERNIER_RECALCUL')||'',version:p.getProperty('CERBERE_DERNIERE_VERSION')||''};}

function diagnostiquerConsolidationCerbere(){
  const erreurs=[],avertissements=[];let p0,r0,cerbere,plan;
  try{p0=chargerCanonCerbereV1();}catch(e){erreurs.push('P0 illisible : '+(e.message||e));}
  try{r0=chargerCanonRecettesCerbereV1();}catch(e){erreurs.push('R0 illisible : '+(e.message||e));}
  try{plan=chargerPlanActionsV4();}catch(e){erreurs.push('Planification illisible : '+(e.message||e));}
  try{cerbere=chargerCerbereV33();}catch(e){erreurs.push('Cerbère illisible : '+(e.message||e));}
  if(p0){if(!(p0.postes||[]).length)erreurs.push('P0 ne contient aucun poste.');if(!Number.isFinite(Number(p0.totaux&&p0.totaux.monetaire)))erreurs.push('Total P0 invalide.');}
  if(r0){if(!(r0.postes||[]).length)erreurs.push('R0 ne contient aucune recette.');if(!(Number(r0.total)>0))avertissements.push('R0 est nul ou négatif.');}
  if(cerbere&&cerbere.ok){if((cerbere.periodes||[]).length!==6)erreurs.push('Cerbère ne produit pas exactement P1–P6.');(cerbere.periodes||[]).forEach((p,i)=>{if(!p.clePilotage)erreurs.push('P'+(i+1)+' n’a pas de clé de pilotage locale.');if(!Number.isFinite(Number(p.budgetDisponible)))erreurs.push('P'+(i+1)+' : budget disponible invalide.');if(!Number.isFinite(Number(p.budgetReparti)))erreurs.push('P'+(i+1)+' : budget réparti invalide.');});}else if(cerbere)erreurs.push('Cerbère a répondu en erreur : '+String(cerbere.erreur||cerbere.stage||'inconnue'));
  return serialiserCerberePourClient_({ok:erreurs.length===0,version:CERBERE_CONSOLIDATION_VERSION,erreurs,avertissements,p0:p0?{version:p0.version,total:p0.totaux&&p0.totaux.monetaire,postes:(p0.postes||[]).length}:null,r0:r0?{version:r0.version,total:r0.total,postes:(r0.postes||[]).length}:null,plan:plan?{version:plan.version,objectifs:(plan.objectifs||[]).length,actions:(plan.actions||[]).length,evenements:(plan.evenements||[]).length}:null,cerbere:cerbere?{ok:cerbere.ok,version:cerbere.version,periodes:(cerbere.periodes||[]).length,duree_ms:cerbere.diagnostic&&cerbere.diagnostic.duree_ms}:null,projection:etatProjectionBudgetSoft()});
}

const CERBERE_COCKPIT_20260902_VERSION='2026-09-03.4';
function chargerCerbereCockpit20260902(){
  const executer=function(){const base=chargerCerbereV374();if(!base||base.ok===false)return base;corrigerSuspensionsActionsEvenements20260903_(base);corrigerReelPilotableDateAchat20260902_(base);const periodes=Array.isArray(base.periodes)?base.periodes:[];periodes.forEach((p,i)=>enrichirCycleCockpitCerbere20260902_(p,i));base.cockpit20260902={version:CERBERE_COCKPIT_20260902_VERSION,appreciation:appreciationCockpitCerbere20260902_(base),doctrine:'Par défaut, l’enveloppe globale P1 suit le pilotable disponible à l’instant t. Un ajustement manuel est mémorisé comme écart à cette capacité. Surplus/déficit à ventiler = enveloppe globale P1 - somme des molettes. Les achats CB alimentent les molettes selon leur date d’achat ; le règlement CB technique est exclu des molettes et vient réduire l’enveloppe globale du cycle suivant selon sa date bancaire.'};return serialiserCerberePourClient_(base);};
  return typeof avecContexteLectureBudgetSoft20260827_==='function'?avecContexteLectureBudgetSoft20260827_('cerbere-cockpit-20260902',executer):executer();
}

function corrigerSuspensionsActionsEvenements20260903_(base){
  (Array.isArray(base&&base.periodes)?base.periodes:[]).forEach(p=>{const v=p&&p.v37;if(!v)return;const l=Array.isArray(v.actionsEvenementsCycle)?v.actionsEvenementsCycle:[];let correctionCf=0,deltaNet=0;l.forEach(x=>{const lib=String(x&&x.libelle||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase(),m=Number(x&&x.montantSigne||0);if(!(m<0)||!/(suspension|suspend|report|reporte|echeance)/.test(lib))return;const a=Math.abs(m);x.montantSigne=arrCockpit20260902_(a);x.effetBudgetaire='charge évitée';correctionCf+=a;deltaNet+=2*a;});if(correctionCf>0){v.cft1=arrCockpit20260902_(Math.max(0,Number(v.cft1||0)-correctionCf));v.correctionSuspensions20260903=arrCockpit20260902_(correctionCf);if(v.actionsEvenementsResume&&Number.isFinite(Number(v.actionsEvenementsResume.net)))v.actionsEvenementsResume.net=arrCockpit20260902_(Number(v.actionsEvenementsResume.net)+deltaNet);}});
}

function corrigerReelPilotableDateAchat20260902_(base){const ops0=lireTable_('Operations')||[],operations=typeof dedoublonnerOperationsCartesBudgetSoft_==='function'?dedoublonnerOperationsCartesBudgetSoft_(ops0):ops0,charges=lireTable_('Charges_fixes')||[],rapprochements=typeof lireRapprochementsChargesFixes==='function'?lireRapprochementsChargesFixes():[],liensCf=typeof construireLiensCfCertainsV377_==='function'?construireLiensCfCertainsV377_(operations,charges,rapprochements):{},maintenant=new Date();(Array.isArray(base.periodes)?base.periodes:[]).forEach(p=>{if(!p||typeof p!=='object')return;const env=Array.isArray(p.enveloppes)?p.enveloppes:[],debut=dateCockpit20260902_(p.periode&&p.periode.debut),fin=dateCockpit20260902_(p.periode&&p.periode.fin);if(!debut||!fin)return;const cats=new Set(env.map(x=>String(x&&x.categorie||'').trim()).filter(Boolean)),reelParCat={};operations.forEach(o=>{const montant=Number(o&&o.montant||0),cat=String(o&&o.categorie||'').trim(),id=String(o&&o.id||'').trim();if(!Number.isFinite(montant)||montant>=0||!cats.has(cat))return;if((id&&liensCf[id])||String(o&&o.charge_fixe_id||'').trim())return;if(typeof estReglementCbTechniqueV377_==='function'&&estReglementCbTechniqueV377_(o))return;const d=dateAchatCockpit20260902_(o);if(!d||d<debut||d>fin||d>maintenant)return;reelParCat[cat]=Number(reelParCat[cat]||0)+Math.abs(montant);});env.forEach(x=>{const cat=String(x&&x.categorie||'').trim();x.reelNetPrevisionnel=arrCockpit20260902_(Number(reelParCat[cat]||0));x.reelPilotableDepuisDebutCycle=x.reelNetPrevisionnel;});});}
function dateAchatCockpit20260902_(o){let d=null;if(typeof dateAchatMetierBudgetSoft_==='function')d=dateAchatMetierBudgetSoft_(o);if(!d)d=dateCockpit20260902_(o&&o.date_achat);if(!d&&typeof dateOperationCouranteBudgetSoft_==='function')d=dateOperationCouranteBudgetSoft_(o);if(!d)d=dateCockpit20260902_(o&&(o.date||o.date_comptable));return d;}
function dateCockpit20260902_(v){if(!v)return null;const d=v instanceof Date?new Date(v):new Date(v);return isNaN(d)?null:d;}
function arrCockpit20260902_(n){return Math.round((Number(n)||0)*100)/100;}
function cleAjustementP1Cerbere20260903_(cle){return 'CERBERE_P1_AJUSTEMENT_'+String(cle||'').replace(/[^A-Za-z0-9_-]/g,'_');}
function lireAjustementP1Cerbere20260903_(cle){const raw=PropertiesService.getDocumentProperties().getProperty(cleAjustementP1Cerbere20260903_(cle)),n=Number(raw);return raw===null||raw===''||!Number.isFinite(n)?0:n;}
function lireCibleP1Cerbere20260903_(cle,pilotableActualise){return Math.max(0,arrCockpit20260902_(Number(pilotableActualise||0)+lireAjustementP1Cerbere20260903_(cle)));}
function memoriserCibleP1Cerbere20260903_(cle,montant,pilotableActualise){const cible=Math.max(0,Number(montant||0)),base=Math.max(0,Number(pilotableActualise||0)),ajustement=arrCockpit20260902_(cible-base);PropertiesService.getDocumentProperties().setProperty(cleAjustementP1Cerbere20260903_(cle),String(ajustement));return{cible:arrCockpit20260902_(cible),ajustement:ajustement};}
function calculerReportCbBancaireCycle20260903_(p){if(!p)return 0;const periode=p.periode||p,ops=lireTable_('Operations')||[];let total=0;ops.forEach(o=>{if(!(typeof estReglementCbTechniqueV377_==='function'&&estReglementCbTechniqueV377_(o)))return;const d=typeof dateOperationBanqueV377_==='function'?dateOperationBanqueV377_(o):dateCockpit20260902_(o&&(o.date_comptable||o.date));if(!d||!(typeof dateDansCycleV377_==='function'?dateDansCycleV377_(d,periode):true))return;const m=Number(o&&o.montant||0);if(m<0)total+=Math.abs(m);});return arrCockpit20260902_(total);}

function enrichirCycleCockpitCerbere20260902_(p,indexCycle){if(!p||typeof p!=='object')return;const v=p.v37||(p.v37={}),env=Array.isArray(p.enveloppes)?p.enveloppes:[];let p0=0,allocation=0,dpt=0,consomme=0,plan=0,depassements=0;env.forEach(x=>{const canon=Math.max(0,Number(x&&x.canon||0)),a=Math.max(0,Number(x&&x.prevu||0)),reel=Math.max(0,Number(x&&x.reelNetPrevisionnel!=null?x.reelNetPrevisionnel:(x&&x.reelImpute||0))),reserve=Math.max(0,Number(x&&x.planifie||0)),engage=reel+reserve;p0+=canon;allocation+=a;consomme+=reel;plan+=reserve;dpt+=Math.max(a,engage);depassements+=Math.max(0,engage-a);x.engageV37=arrCockpit20260902_(engage);x.resteV37=arrCockpit20260902_(a-reel);x.dpt1=arrCockpit20260902_(Math.max(a,engage));});const het=Math.max(0,Number(v.het1!=null?v.het1:(v.horsPilotableAControler||0))),baseActualisee=Math.max(0,Number(v.rt1||0)-Number(v.cft1||0)-het),reportCb=Number(indexCycle||0)>0?calculerReportCbBancaireCycle20260903_(p):0,actualise=Math.max(0,baseActualisee-reportCb),cible=lireCibleP1Cerbere20260903_(p.clePilotage,actualise),retGlobal=cible-consomme,marge=cible-allocation,arr=arrCockpit20260902_;v.cockpit20260902={p0Total:arr(p0),p1Total:arr(cible),p1Cible:arr(cible),ajustementP1:arr(cible-actualise),budgetRepartiMolettes:arr(allocation),aRepartirDansPostes:arr(marge),budgetPilotableActualise:arr(actualise),budgetPilotableAvantReportCb:arr(baseActualisee),reportCbCycle:arr(reportCb),capacitePilotable:arr(actualise),surplusVsP0:arr(cible-p0),margeARepartir:arr(marge),surplusCapaciteVsAllocation:arr(actualise-allocation),consommePilotable:arr(consomme),reservePlan:arr(plan),ret1:arr(retGlobal),dpt1:arr(dpt),depassements:arr(depassements),het1:arr(het),detailActualise:{recettesReevaluees:arr(v.rt1),chargesFixesReevaluees:arr(v.cft1),horsPilotableEtImprevus:arr(het),reportCbBancaire:arr(reportCb)},formuleActualisee:'Enveloppe P1 = recettes réévaluées - charges fixes réévaluées - hors-pilotable - report CB bancaire du cycle suivant + ajustement manuel',formuleVentilation:'Surplus/déficit à ventiler = enveloppe P1 - somme des molettes',propositionProjetPossible:false,datePilotable:'date d’achat prioritaire pour le pilotable ; date bancaire pour la trésorerie et le cycle suivant'};v.ret1=arr(retGlobal);v.dpt1=arr(dpt);v.disponibleEnveloppes=arr(retGlobal);p.resteBudgetPilotable=arr(retGlobal);p.budgetReparti=arr(allocation);}

function sauvegarderPilotageCerbere20260903(d){d=d||{};const cle=String(d.cle||'').trim(),cible=Math.max(0,Number(d.p1Cible||0)),actualise=Math.max(0,Number(d.pilotableActualise||0)),postes=Array.isArray(d.postes)?d.postes:[];if(!cle)throw new Error('Cycle Cerbère manquant.');sauvegarderBudgetPeriodeCerbereV33({cle:cle,postes:postes});const memo=memoriserCibleP1Cerbere20260903_(cle,cible,actualise);invaliderProjectionBudgetSoft_('cerbere-pilotage-p1');return{ok:true,cle:cle,p1Cible:memo.cible,ajustementP1:memo.ajustement};}

function listerImprevusCerbere20260903(clePilotage){
  const b=chargerCerbereV374(),p=(b&&b.periodes||[]).find(x=>String(x&&x.clePilotage||'')===String(clePilotage||''))||(b&&b.periodes||[])[0];if(!p)return{ok:false,lignes:[],depenses:0,recettes:0,net:0};
  const operations=lireTable_('Operations')||[],charges=lireTable_('Charges_fixes')||[],categories=lireTable_('Categories')||[],rap=typeof lireRapprochementsChargesFixes==='function'?lireRapprochementsChargesFixes():[],liens=typeof construireLiensChargesFixesCommuns_==='function'?construireLiensChargesFixesCommuns_(operations,charges,rap):{},periode=p.periode||p,p0Cats=new Set((b.p0&&b.p0.postes||[]).map(x=>String(x&&x.categorie||'').trim()).filter(Boolean)),r0Cats=new Set((b.recettesCanon&&b.recettesCanon.postes||[]).map(x=>String(x&&x.categorie||'').trim()).filter(Boolean)),types={},events=typeof lireFeuilleDynamiquePlan_==='function'?lireFeuilleDynamiquePlan_('Plan_Evenements'):[],opsEvents=new Set(events.map(e=>String(e&&e.operation_reelle_id||'').trim()).filter(Boolean));p0Cats.add('Divers');categories.forEach(c=>types[String(c&&c.nom||'').trim()]=typeof normaliserV377_==='function'?normaliserV377_(c&&c.type):String(c&&c.type||'').toLowerCase());
  const lignes=[];let depenses=0,recettes=0;operations.forEach(o=>{const d=typeof dateImputationCerbereV377_==='function'?dateImputationCerbereV377_(o):dateCockpit20260902_(o&&o.date),m=Number(o&&o.montant||0),cat=String(o&&o.categorie||'').trim(),id=String(o&&o.id||'').trim();if(!d||!(typeof dateDansCycleV377_==='function'?dateDansCycleV377_(d,periode):true)||!m||opsEvents.has(id)||liens[id]||types[cat]==='tresorerie'||(typeof estReglementCbTechniqueV377_==='function'&&estReglementCbTechniqueV377_(o)))return;if(m<0&&p0Cats.has(cat))return;if(m>0&&r0Cats.has(cat))return;if(m<0)depenses+=Math.abs(m);else recettes+=m;lignes.push({id:id,date:Utilities.formatDate(d,Session.getScriptTimeZone()||'Europe/Paris','yyyy-MM-dd'),montant:arrCockpit20260902_(m),categorie:cat,libelle:String(o&&o.libelle||o&&o.libelle_bancaire||'')});});
  return{ok:true,clePilotage:p.clePilotage,lignes:lignes,depenses:arrCockpit20260902_(depenses),recettes:arrCockpit20260902_(recettes),net:arrCockpit20260902_(recettes-depenses),categories:categories.map(c=>String(c&&c.nom||'').trim()).filter(Boolean).sort()};
}
function reclasserImprevuCerbere20260903(idOperation,nouvelleCategorie){if(typeof rapprocherPrevisionnelReelBudgetSoft==='function')return rapprocherPrevisionnelReelBudgetSoft({type:'imprevu_categorie',operation_id:idOperation,categorie:nouvelleCategorie});throw new Error('Moteur unique de rapprochement indisponible.');}

function appreciationCockpitCerbere20260902_(base){const p=Array.isArray(base&&base.periodes)?base.periodes[0]:null;if(!p)return{niveau:'vert',emoji:'🌤️',titre:'Situation à observer',resume:'Aucun cycle courant disponible.',consigne:''};const v=p.v37||{},c=v.cockpit20260902||{},env=Array.isArray(p.enveloppes)?p.enveloppes:[],debut=new Date((p.periode||p).debut),fin=new Date((p.periode||p).fin),now=new Date(),total=Math.max(1,fin-debut),ratio=Math.max(0,Math.min(1,(now-debut)/total)),alertes=[];env.forEach(x=>{const allocation=Math.max(0,Number(x&&x.prevu||0)),reel=Math.max(0,Number(x&&x.reelNetPrevisionnel!=null?x.reelNetPrevisionnel:(x&&x.reelImpute||0)));if(!allocation&&reel<=0)return;const part=allocation>0?reel/allocation:1,ecart=(part-ratio)*100;if(reel>allocation+.009)alertes.push({niveau:2,texte:String(x.categorie||'Poste')+' dépassé'});else if(ecart>25)alertes.push({niveau:2,texte:String(x.categorie||'Poste')+' très rapide'});else if(ecart>10)alertes.push({niveau:1,texte:String(x.categorie||'Poste')+' un peu rapide'});});if(Number(c.margeARepartir||0)<-.009)alertes.push({niveau:2,texte:'Économies à trouver : '+formatEuroCockpit20260902_(Math.abs(c.margeARepartir))});const niveau=Math.max(0,...alertes.map(x=>x.niveau)),info=alertes.sort((a,b)=>b.niveau-a.niveau)[0];if(niveau>=2)return{niveau:'rouge',emoji:'⛈️',titre:'Arbitrage nécessaire',resume:'Le cycle demande un ajustement du pilotable.',consigne:info?info.texte:''};if(niveau===1)return{niveau:'orange',emoji:'🌧️',titre:'Cap à surveiller',resume:'La situation reste récupérable, mais un poste mérite l’attention.',consigne:info?info.texte:''};const marge=Number(c.margeARepartir||0);return{niveau:'vert',emoji:'🌤️',titre:'Cap tenu',resume:'Le rythme du pilotable reste compatible avec le cycle.',consigne:marge>0?'Surplus à ventiler : '+formatEuroCockpit20260902_(marge):'P1 entièrement réparti.'};}
function auditerCockpitPilotable20260902(){const b=chargerCerbereCockpit20260902(),p=b&&b.periodes&&b.periodes[0],c=p&&p.v37&&p.v37.cockpit20260902;return{ok:!!p,periode:p&&p.periode,p0:c&&c.p0Total,p1:c&&c.p1Total,pilotableActualise:c&&c.budgetPilotableActualise,surplusP0:c&&c.surplusVsP0,marge:c&&c.margeARepartir,reparti:c&&c.budgetRepartiMolettes,aRepartir:c&&c.aRepartirDansPostes,reelPilotable:c&&c.consommePilotable,ajustementP1:c&&c.ajustementP1,reportCbCycle:c&&c.reportCbCycle};}
function formatEuroCockpit20260902_(n){return Utilities.formatString('%.2f €',Math.round((Number(n)||0)*100)/100);}
