const CERBERE_EXPRESS_SNAPSHOT_VERSION='2026-09-03.2';
const CERBERE_EXPRESS_SNAPSHOT_PREFIX='CERBERE_EXPRESS_SNAPSHOT_';
const CERBERE_EXPRESS_SNAPSHOT_CHUNK=7000;

function chargerSnapshotCerbereExpress20260827(){const t0=Date.now(),props=PropertiesService.getDocumentProperties(),meta=lireMetaSnapshotCerbereExpress20260827_(props);if(!meta)return{ok:true,version:CERBERE_EXPRESS_SNAPSHOT_VERSION,disponible:false,perime:true,dureeLectureMs:Date.now()-t0};const vue=lireCorpsSnapshotCerbereExpress20260827_(props,meta);if(!vue)return{ok:true,version:CERBERE_EXPRESS_SNAPSHOT_VERSION,disponible:false,perime:true,corrompu:true,dureeLectureMs:Date.now()-t0};const revisionCourante=empreinteSourcesCerbereExpress20260827_(),perime=String(meta.revision||'')!==revisionCourante;return{ok:true,version:CERBERE_EXPRESS_SNAPSHOT_VERSION,disponible:true,perime,revision:String(meta.revision||''),revisionCourante,genereLe:String(meta.genereLe||''),tailleCompressee:Number(meta.tailleCompressee||0),morceaux:Number(meta.morceaux||0),dureeLectureMs:Date.now()-t0,vue};}

function rafraichirSnapshotCerbereExpress20260827(){const lock=LockService.getDocumentLock();if(!lock.tryLock(1000)){const courant=chargerSnapshotCerbereExpress20260827();return{ok:!!(courant&&courant.disponible),version:CERBERE_EXPRESS_SNAPSHOT_VERSION,rafraichissementEnCours:true,snapshot:courant};}const t0=Date.now();try{const calculer=function(){return chargerVueCerbereExpressSansContexte20260827_();};const vue=typeof avecContexteLectureBudgetSoft20260827_==='function'?avecContexteLectureBudgetSoft20260827_('cerbere-express-refresh',calculer):calculer();if(!vue||vue.ok===false)throw new Error(String(vue&&vue.erreur||'Cerbère Express indisponible'));const revision=empreinteSourcesCerbereExpress20260827_(),json=JSON.stringify(vue),compresse=encoderSnapshotCerbereExpress20260827_(json),morceaux=[];for(let i=0;i<compresse.length;i+=CERBERE_EXPRESS_SNAPSHOT_CHUNK)morceaux.push(compresse.slice(i,i+CERBERE_EXPRESS_SNAPSHOT_CHUNK));const props=PropertiesService.getDocumentProperties();supprimerAncienSnapshotCerbereExpress20260827_(props);morceaux.forEach((part,i)=>props.setProperty(CERBERE_EXPRESS_SNAPSHOT_PREFIX+'PART_'+i,part));const meta={version:CERBERE_EXPRESS_SNAPSHOT_VERSION,revision,genereLe:String(vue.genereLe||Utilities.formatDate(new Date(),Session.getScriptTimeZone(),"yyyy-MM-dd'T'HH:mm:ss")),morceaux:morceaux.length,tailleCompressee:compresse.length};props.setProperty(CERBERE_EXPRESS_SNAPSHOT_PREFIX+'META',JSON.stringify(meta));const relu=lireCorpsSnapshotCerbereExpress20260827_(props,meta);if(JSON.stringify(relu)!==json){supprimerAncienSnapshotCerbereExpress20260827_(props);throw new Error('Échec du contrôle d’intégrité du snapshot Cerbère Express.');}return{ok:true,version:CERBERE_EXPRESS_SNAPSHOT_VERSION,revision,genereLe:meta.genereLe,morceaux:morceaux.length,tailleCompressee:compresse.length,dureeCalculMs:Date.now()-t0,roundTripOk:true,vue:relu};}finally{lock.releaseLock();}}

function invaliderSnapshotCerbereExpress20260827(){const props=PropertiesService.getDocumentProperties();supprimerAncienSnapshotCerbereExpress20260827_(props);return{ok:true,version:CERBERE_EXPRESS_SNAPSHOT_VERSION};}
function auditerSnapshotCerbereExpress20260827(){const t0=Date.now(),s=chargerSnapshotCerbereExpress20260827(),out={ok:!!(s&&s.disponible&&s.vue&&s.vue.ok),version:CERBERE_EXPRESS_SNAPSHOT_VERSION,disponible:!!(s&&s.disponible),perime:!!(s&&s.perime),genereLe:s&&s.genereLe||'',dureeLectureMs:Date.now()-t0,tailleCompressee:Number(s&&s.tailleCompressee||0),morceaux:Number(s&&s.morceaux||0),cycle:s&&s.vue&&s.vue.cycle||null,pilotable:s&&s.vue&&s.vue.pilotable?{allocation:s.vue.pilotable.allocation,consomme:s.vue.pilotable.consomme,reste:s.vue.pilotable.reste,aVentiler:s.vue.pilotable.aVentiler}:null,meteo:s&&s.vue&&s.vue.meteo||null};console.log(JSON.stringify(out));return out;}

function empreinteSourcesCerbereExpress20260827_(){const ss=SpreadsheetApp.getActiveSpreadsheet(),fichier=DriveApp.getFileById(ss.getId()),modifieLe=fichier.getLastUpdated().getTime(),props=PropertiesService.getDocumentProperties().getProperties(),utiles={};Object.keys(props).sort().forEach(k=>{if(String(k).indexOf(CERBERE_EXPRESS_SNAPSHOT_PREFIX)===0)return;utiles[k]=props[k];});const jour=Utilities.formatDate(new Date(),Session.getScriptTimeZone(),'yyyy-MM-dd'),brut=[CERBERE_EXPRESS_SNAPSHOT_VERSION,String(modifieLe),jour,JSON.stringify(utiles)].join('|'),digest=Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,brut,Utilities.Charset.UTF_8);return digest.map(b=>('0'+((b+256)%256).toString(16)).slice(-2)).join('');}
function lireMetaSnapshotCerbereExpress20260827_(props){const raw=props.getProperty(CERBERE_EXPRESS_SNAPSHOT_PREFIX+'META');if(!raw)return null;try{const m=JSON.parse(raw);if(!m||m.version!==CERBERE_EXPRESS_SNAPSHOT_VERSION||!(Number(m.morceaux)>0))return null;return m;}catch(e){return null;}}
function lireCorpsSnapshotCerbereExpress20260827_(props,meta){try{let raw='';for(let i=0;i<Number(meta.morceaux||0);i++){const part=props.getProperty(CERBERE_EXPRESS_SNAPSHOT_PREFIX+'PART_'+i);if(part==null)return null;raw+=part;}return JSON.parse(decoderSnapshotCerbereExpress20260827_(raw));}catch(e){return null;}}
function encoderSnapshotCerbereExpress20260827_(texte){return Utilities.base64EncodeWebSafe(Utilities.gzip(Utilities.newBlob(String(texte||''),'application/json','cerbere-express.json')).getBytes());}
function decoderSnapshotCerbereExpress20260827_(texte){return Utilities.ungzip(Utilities.newBlob(Utilities.base64DecodeWebSafe(String(texte||'')),'application/gzip','cerbere-express.json.gz')).getDataAsString('UTF-8');}
function supprimerAncienSnapshotCerbereExpress20260827_(props){const toutes=props.getProperties();Object.keys(toutes).forEach(k=>{if(String(k).indexOf(CERBERE_EXPRESS_SNAPSHOT_PREFIX)===0)props.deleteProperty(k);});}
