const CERBERE_EXPRESS_VIEW_VERSION = '2026-09-13.2';

function chargerVueCerbereExpress20260827(){
  const global=typeof lireModuleSnapshotGlobalBudgetSoft20260906_==='function'?lireModuleSnapshotGlobalBudgetSoft20260906_('cerbereExpress'):null;
  if(global){global.performance=Object.assign({},global.performance||{},{source:'snapshot_global',dureeMs:0});return global;}
  if(typeof avecContexteLectureBudgetSoft20260827_==='function')return avecContexteLectureBudgetSoft20260827_('cerbere-express-calcul-frais',chargerVueCerbereExpressSansContexte20260827_);
  return chargerVueCerbereExpressSansContexte20260827_();
}
function chargerVueCerbereExpressSansContexte20260827_(){
  const e=chargerCerbereExpress20260827();if(!e||e.ok===false)return e||{ok:false,erreur:'Cerbère Express indisponible'};
  const lignes=(e.pilotable&&e.pilotable.lignes||[]).map(x=>({categorie:x.categorie,allocation:Number(x.allocation||0),consomme:Number(x.consomme||0),reste:Number(x.reste||0),partConsommee:Number(x.partConsommee||0),partTempsPct:Number(x.partTempsPct||0),niveau:x.vigilance&&x.vigilance.niveau||'vert',libelle:x.vigilance&&x.vigilance.libelle||'Cap tenu',message:x.vigilance&&x.vigilance.message||''}));
  const pluxee=e.pluxee&&e.pluxee.disponible?{disponible:true,soldeReel:Number(e.pluxee.soldeReel||0),soldeTheorique:Number(e.pluxee.soldeTheorique||0),ecart:Number(e.pluxee.ecartReelTheorique||0),progressionPct:Number(e.pluxee.progressionPct||0),lignes:(e.pluxee.lignes||[]).map(x=>({categorie:x.categorie,allocation:Number(x.allocation||0),consomme:Number(x.consomme||0),reste:Number(x.reste||0),partConsommee:Number(x.partConsommee||0),partTempsPct:Number(x.partTempsPct||0),niveau:x.vigilance&&x.vigilance.niveau||'vert',message:x.vigilance&&x.vigilance.message||''}))}:{disponible:false};
  const rouges=lignes.filter(x=>x.niveau==='rouge').length,oranges=lignes.filter(x=>x.niveau==='orange').length,ctx=e.contexteDecision||{},ref=e.referenceEP||{};
  return{ok:true,version:CERBERE_EXPRESS_VIEW_VERSION,moteurVersion:e.version,moteurSource:e.moteurSource||'',cockpitVersion:e.cockpitVersion||'',genereLe:e.genereLe,cycle:e.cycle,meteo:e.meteo,consigneSaillante:e.consigneSaillante,pilotable:{allocation:Number(e.pilotable&&e.pilotable.allocation||0),consomme:Number(e.pilotable&&e.pilotable.consomme||0),reste:Number(e.pilotable&&e.pilotable.reste||0),reparti:Number(e.pilotable&&e.pilotable.reparti||0),lignes,rouges,oranges},pluxee,decision:{ep:Number(ctx.ep||0),epDisponible:Number(ctx.epDisponible||0),epSource:String(ctx.epSource||ref.source||''),p0Reference:Number(ref.totalP0||0),prochainCycleEp:Number(ctx.prochainCycleEp||0),reportCbCycleSuivant:Number(ctx.reportCbCycleSuivant||0),epDiffereEstimeCycleSuivant:Number(ctx.epDiffereEstimeCycleSuivant||0)},performance:e.performance||{},sourceBudgetSoft:'recalcul_secours',doctrine:'Cerbère Express publie exclusivement la décision EP et son rythme de consommation.'};
}
function ouvrirCerbereExpress20260827(){const html=HtmlService.createTemplateFromFile('CerbereExpressEpMobile20260913').evaluate().setTitle('Cerbère Express');SpreadsheetApp.getUi().showSidebar(html);}
function installerMenuCerbereExpress20260827(){SpreadsheetApp.getUi().createMenu('🐺 Cerbère Express').addItem('Ouvrir Cerbère Express','ouvrirCerbereExpress20260827').addToUi();return{ok:true,version:CERBERE_EXPRESS_VIEW_VERSION,message:'Menu Cerbère Express installé dans Google Sheets.'};}
function auditerVueCerbereExpress20260827(){const v=chargerVueCerbereExpress20260827();const out={ok:!!(v&&v.ok),version:v&&v.version,moteurVersion:v&&v.moteurVersion,sourceBudgetSoft:v&&v.sourceBudgetSoft||'',revisionBudgetSoft:v&&v.revisionBudgetSoft||'',cycle:v&&v.cycle,meteo:v&&v.meteo,consigneSaillante:v&&v.consigneSaillante,pilotable:v&&v.pilotable?{allocation:v.pilotable.allocation,consomme:v.pilotable.consomme,reste:v.pilotable.reste}:null,pluxee:v&&v.pluxee,decision:v&&v.decision,aucunP:!(v&&v.contexte)&&!(v&&v.referenceP1)};out.ok=out.ok&&out.aucunP;console.log(JSON.stringify(out));return out;}
function auditerPerformanceCerbereExpress20260827(){const t=Date.now(),v=chargerVueCerbereExpress20260827(),dureeMs=Date.now()-t;const out={ok:!!(v&&v.ok),version:CERBERE_EXPRESS_VIEW_VERSION,dureeMs,dureeSecondes:Math.round(dureeMs/100)/10,source:v&&v.sourceBudgetSoft||'recalcul_secours',revisionBudgetSoft:v&&v.revisionBudgetSoft||''};console.log('[PERF Cerbere Express] '+JSON.stringify(out));return out;}
