const BUDGETSOFT_VERSION = '0.7';

const TABLES = {
  Parametres: ['cle', 'valeur'],
  Comptes: ['id', 'nom', 'type', 'solde_initial', 'actif'],
  Operations: ['id', 'date', 'libelle', 'categorie', 'compte', 'montant', 'type', 'commentaire', 'cree_le', 'modifie_le'],
  Charges_fixes: ['id', 'libelle', 'categorie', 'compte', 'montant', 'type', 'jour_execution', 'date_debut', 'date_fin', 'actif', 'commentaire', 'frequence', 'libelle_bancaire', 'tolerance', 'nature'],
  Budget: ['id', 'mois', 'type', 'poste', 'prevu', 'reel'],
  Actifs: ['id', 'nom', 'type', 'valeur', 'date_valeur'],
  Dettes: ['id', 'nom', 'capital_restant', 'mensualite', 'taux', 'date_fin'],
  Credits: ['id', 'nom', 'capital_restant', 'mensualite', 'taux', 'date_debut', 'date_fin'],
  Objectifs: ['id', 'nom', 'montant_cible', 'montant_actuel', 'date_cible', 'statut'],
  Categories: ['id', 'nom', 'type', 'couleur', 'actif']
};

function onOpen() { SpreadsheetApp.getUi().createMenu('BudgetSoft').addItem('Initialiser / mettre à jour','initialiserBudgetSoft').addItem('Générer les charges récurrentes','genererChargesFixes').addItem('Vérifier la configuration','verifierConfiguration').addToUi(); }
function doGet(){return HtmlService.createTemplateFromFile('Index').evaluate().setTitle('BudgetSoft').setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL);}
function inclure(nomFichier){return HtmlService.createHtmlOutputFromFile(nomFichier).getContent();}
function initialiserBudgetSoft(){const ss=SpreadsheetApp.getActiveSpreadsheet();Object.entries(TABLES).forEach(([nom,entetes])=>{let feuille=ss.getSheetByName(nom);if(!feuille)feuille=ss.insertSheet(nom);if(feuille.getLastRow()===0)feuille.getRange(1,1,1,entetes.length).setValues([entetes]);else{const largeur=Math.max(feuille.getLastColumn(),1),presentes=feuille.getRange(1,1,1,largeur).getValues()[0].map(v=>String(v||'').trim()),manquantes=entetes.filter(e=>!presentes.includes(e));if(manquantes.length)feuille.getRange(1,largeur+1,1,manquantes.length).setValues([manquantes]);}feuille.setFrozenRows(1);feuille.getRange(1,1,1,entetes.length).setFontWeight('bold').setBackground('#147d64').setFontColor('#ffffff');feuille.autoResizeColumns(1,entetes.length);});ajouterDonneesInitiales_();mettreAJourVersion_();PropertiesService.getDocumentProperties().setProperty('BUDGETSOFT_INITIALISE','true');SpreadsheetApp.getUi().alert('BudgetSoft est initialisé et à jour (version '+BUDGETSOFT_VERSION+').');}
function verifierConfiguration(){const ss=SpreadsheetApp.getActiveSpreadsheet(),manquantes=Object.keys(TABLES).filter(n=>!ss.getSheetByName(n)),colonnesManquantes=[];Object.entries(TABLES).forEach(([nom,entetes])=>{const f=ss.getSheetByName(nom);if(!f||f.getLastRow()===0)return;const largeur=Math.max(f.getLastColumn(),1),presentes=f.getRange(1,1,1,largeur).getValues()[0].map(v=>String(v||'').trim());entetes.filter(e=>!presentes.includes(e)).forEach(e=>colonnesManquantes.push(nom+'.'+e));});let message='Configuration valide. BudgetSoft est prêt.';if(manquantes.length)message='Onglets manquants : '+manquantes.join(', ');else if(colonnesManquantes.length)message='Colonnes manquantes : '+colonnesManquantes.join(', ');SpreadsheetApp.getUi().alert(message);return{ok:!manquantes.length&&!colonnesManquantes.length,manquantes,colonnesManquantes};}
function chargerToutesLesDonnees(){verifierInitialisation_();const generation=genererChargesFixes(),resultat={};Object.keys(TABLES).forEach(n=>resultat[n]=lireTable_(n));resultat.meta={version:BUDGETSOFT_VERSION,chargeLe:new Date().toISOString(),generation};return resultat;}
function lireTable(nom){verifierNomTable_(nom);verifierInitialisation_();return lireTable_(nom);}
function enregistrerLigne(nom,ligne){verifierNomTable_(nom);verifierInitialisation_();if(!ligne||typeof ligne!=='object')throw new Error('Donnée invalide.');const feuille=SpreadsheetApp.getActiveSpreadsheet().getSheetByName(nom),entetes=TABLES[nom],maintenant=new Date().toISOString(),copie=Object.assign({},ligne);if(nom==='Comptes'){copie.nom=String(copie.nom||'').trim();if(!copie.nom)throw new Error('Le nom du compte est obligatoire.');copie.type=String(copie.type||'courant').trim();copie.solde_initial=convertirNombre_(copie.solde_initial);copie.actif=convertirBooleen_(copie.actif);}if(nom==='Operations')normaliserOperation_(copie);if(nom==='Charges_fixes')normaliserChargeFixe_(copie);if(entetes.includes('id')&&!copie.id)copie.id=Utilities.getUuid();if(entetes.includes('cree_le')&&!copie.cree_le)copie.cree_le=maintenant;if(entetes.includes('modifie_le'))copie.modifie_le=maintenant;const verrou=LockService.getDocumentLock();verrou.waitLock(10000);try{const idIndex=entetes.indexOf('id');let ligneCible=-1;if(idIndex>=0&&copie.id&&feuille.getLastRow()>1){const ids=feuille.getRange(2,idIndex+1,feuille.getLastRow()-1,1).getValues().flat(),position=ids.findIndex(id=>String(id)===String(copie.id));if(position>=0)ligneCible=position+2;}const valeurs=entetes.map(cle=>normaliserValeur_(copie[cle]));if(ligneCible>0)feuille.getRange(ligneCible,1,1,entetes.length).setValues([valeurs]);else feuille.appendRow(valeurs);}finally{verrou.releaseLock();}return copie;}
function normaliserChargeFixe_(copie){copie.libelle=String(copie.libelle||'').trim();copie.compte=String(copie.compte||'').trim();copie.categorie=String(copie.categorie||'').trim();copie.type=String(copie.type||'depense').toLowerCase();copie.montant=Math.abs(convertirNombre_(copie.montant));copie.jour_execution=Math.max(1,Math.min(31,parseInt(copie.jour_execution,10)||1));copie.date_debut=copie.date_debut?new Date(copie.date_debut):new Date();copie.date_fin=copie.date_fin?new Date(copie.date_fin):'';copie.actif=convertirBooleen_(copie.actif);copie.frequence=normaliserFrequence_(copie.frequence);copie.libelle_bancaire=String(copie.libelle_bancaire||'').trim();copie.tolerance=copie.tolerance===''||copie.tolerance==null?0.50:Math.abs(convertirNombre_(copie.tolerance));copie.nature=String(copie.nature||'Autre').trim();if(!copie.libelle||!copie.compte)throw new Error('Le libellé et le compte sont obligatoires.');if(!copie.libelle_bancaire)throw new Error('Le libellé bancaire est obligatoire.');if(isNaN(copie.date_debut.getTime()))throw new Error('La date de début est invalide.');if(copie.date_fin instanceof Date&&isNaN(copie.date_fin.getTime()))throw new Error('La date de fin est invalide.');if(copie.date_fin instanceof Date&&copie.date_fin<copie.date_debut)throw new Error('La date de fin doit être postérieure à la date de début.');}
function genererChargesFixes(){verifierInitialisation_();const charges=lireTable_('Charges_fixes').filter(c=>convertirBooleen_(c.actif));if(!charges.length)return{creees:0,ignorees:0,erreurs:[]};const operations=lireTable_('Operations'),marqueurs=new Set(operations.map(o=>extraireMarqueur_(o.commentaire)).filter(Boolean)),aujourdHui=debutJour_(new Date());let creees=0,ignorees=0;const erreurs=[];charges.forEach(charge=>{try{const debut=debutJour_(new Date(charge.date_debut)),fin=charge.date_fin?finJour_(new Date(charge.date_fin)):null;if(isNaN(debut.getTime()))throw new Error('date de début invalide');calculerEcheancesJusqua_(charge,debut,fin,aujourdHui).forEach(dateOperation=>{const cle=cleRecurrence_(charge.id,dateOperation);if(marqueurs.has(cle)){ignorees++;return;}enregistrerLigne('Operations',{date:dateOperation,libelle:charge.libelle,categorie:charge.categorie,compte:charge.compte,montant:charge.montant,type:charge.type||'depense',commentaire:[charge.commentaire||'','[RECURRENCE:'+cle+']'].filter(Boolean).join(' ')});marqueurs.add(cle);creees++;});}catch(e){erreurs.push((charge.libelle||charge.id||'Charge')+' : '+e.message);}});return{creees,ignorees,erreurs};}
function calculerEcheancesJusqua_(charge,debut,fin,limite){if(limite<debut)return[];const borne=fin&&fin<limite?fin:limite,frequence=normaliserFrequence_(charge.frequence),jour=Number(charge.jour_execution)||debut.getDate(),resultats=[];let curseur;if(frequence==='Quotidienne'){curseur=new Date(debut);while(curseur<=borne){resultats.push(new Date(curseur));curseur.setDate(curseur.getDate()+1);}return resultats;}if(frequence==='Hebdomadaire'){curseur=new Date(debut);while(curseur<=borne){resultats.push(new Date(curseur));curseur.setDate(curseur.getDate()+7);}return resultats;}const pasMois={Mensuelle:1,Trimestrielle:3,Semestrielle:6,Annuelle:12}[frequence]||1;curseur=creerDateMensuelle_(debut.getFullYear(),debut.getMonth(),jour);if(curseur<debut)curseur=creerDateMensuelle_(debut.getFullYear(),debut.getMonth()+pasMois,jour);while(curseur<=borne){resultats.push(new Date(curseur));curseur=creerDateMensuelle_(curseur.getFullYear(),curseur.getMonth()+pasMois,jour);}return resultats;}
function creerDateMensuelle_(annee,mois,jour){const premier=new Date(annee,mois,1),dernierJour=new Date(premier.getFullYear(),premier.getMonth()+1,0).getDate();return new Date(premier.getFullYear(),premier.getMonth(),Math.min(Math.max(1,jour),dernierJour));}
function normaliserFrequence_(valeur){const texte=String(valeur||'Mensuelle').trim().toLowerCase(),c={quotidienne:'Quotidienne',quotidien:'Quotidienne',hebdomadaire:'Hebdomadaire',hebdo:'Hebdomadaire',mensuelle:'Mensuelle',mensuel:'Mensuelle',trimestrielle:'Trimestrielle',trimestriel:'Trimestrielle',semestrielle:'Semestrielle',semestriel:'Semestrielle',annuelle:'Annuelle',annuel:'Annuelle'};return c[texte]||'Mensuelle';}
function cleRecurrence_(id,date){return String(id)+':'+Utilities.formatDate(date,Session.getScriptTimeZone(),'yyyy-MM-dd');}
function extraireMarqueur_(commentaire){const match=String(commentaire||'').match(/\[RECURRENCE:([^\]]+)\]/);return match?match[1]:'';}
function debutJour_(date){return new Date(date.getFullYear(),date.getMonth(),date.getDate());}
function finJour_(date){return new Date(date.getFullYear(),date.getMonth(),date.getDate(),23,59,59,999);}
function supprimerLigne(nom,id){verifierNomTable_(nom);verifierInitialisation_();const entetes=TABLES[nom],idIndex=entetes.indexOf('id');if(idIndex<0)throw new Error('Cette table ne comporte pas d’identifiant.');const feuille=SpreadsheetApp.getActiveSpreadsheet().getSheetByName(nom);if(feuille.getLastRow()<2)return false;const ids=feuille.getRange(2,idIndex+1,feuille.getLastRow()-1,1).getValues().flat(),position=ids.findIndex(v=>String(v)===String(id));if(position<0)return false;feuille.deleteRow(position+2);return true;}
function lireTable_(nom){const feuille=SpreadsheetApp.getActiveSpreadsheet().getSheetByName(nom);if(!feuille||feuille.getLastRow()<2)return[];const entetes=TABLES[nom],valeurs=feuille.getRange(2,1,feuille.getLastRow()-1,entetes.length).getValues();return valeurs.filter(l=>l.some(v=>v!==''&&v!==null)).map(l=>Object.fromEntries(entetes.map((cle,i)=>[cle,serialiserValeur_(l[i])])));}
function normaliserOperation_(copie){copie.libelle=String(copie.libelle||'').trim();copie.compte=String(copie.compte||'').trim();copie.categorie=String(copie.categorie||'').trim();copie.type=String(copie.type||'depense').toLowerCase();copie.date=copie.date?new Date(copie.date):new Date();if(!copie.libelle)throw new Error('Le libellé est obligatoire.');if(!copie.compte)throw new Error('Le compte est obligatoire.');if(isNaN(copie.date.getTime()))throw new Error('La date est invalide.');const montant=Math.abs(convertirNombre_(copie.montant));copie.montant=copie.type==='depense'?-montant:montant;}

function ajouterDonneesInitiales_(){
  const ss=SpreadsheetApp.getActiveSpreadsheet(),categories=ss.getSheetByName('Categories');
  if(categories.getLastRow()>1){
    const valeurs=categories.getRange(2,1,categories.getLastRow()-1,TABLES.Categories.length).getValues();
    let banqueExiste=valeurs.some(r=>String(r[1]||'').trim().toLowerCase()==='banque');
    for(let i=valeurs.length-1;i>=0;i--){if(String(valeurs[i][1]||'').trim().toLowerCase()==='frais bancaires'){if(!banqueExiste){categories.getRange(i+2,2).setValue('Banque');banqueExiste=true;}else categories.deleteRow(i+2);}}
  }
  const operations=ss.getSheetByName('Operations');
  if(operations&&operations.getLastRow()>1){const colCategorie=TABLES.Operations.indexOf('categorie')+1,plage=operations.getRange(2,colCategorie,operations.getLastRow()-1,1),vals=plage.getValues();let change=false;vals.forEach(r=>{if(String(r[0]||'').trim().toLowerCase()==='frais bancaires'){r[0]='Banque';change=true;}});if(change)plage.setValues(vals);}
  const categoriesParDefaut=[
    ['Logement','depense'],['Courses','depense'],['Transport','depense'],['Santé','depense'],['Loisirs','depense'],
    ['Revenus','revenu'],['Salaire','revenu'],['France Travail','revenu'],['Cours','revenu'],['Divers','revenu'],['Revenus fonciers','revenu'],
    ['Épargne','epargne'],['Crédits','depense'],['Assurances','depense'],['Télécommunications','depense'],['Abonnements','depense'],['Impôts','depense'],['Animaux','depense'],['Banque','depense']
  ];
  // Corrige aussi le type de catégories déjà créées lors d'une version précédente.
  if(categories.getLastRow()>1){const nomsRevenus=new Set(['cours','divers','revenus fonciers']);const plage=categories.getRange(2,1,categories.getLastRow()-1,TABLES.Categories.length),vals=plage.getValues();let change=false;vals.forEach(r=>{if(nomsRevenus.has(String(r[1]||'').trim().toLowerCase())&&String(r[2]||'').trim().toLowerCase()!=='revenu'){r[2]='revenu';change=true;}});if(change)plage.setValues(vals);}
  const existantes=new Set(categories.getLastRow()>1?categories.getRange(2,2,categories.getLastRow()-1,1).getValues().flat().map(v=>String(v||'').trim().toLowerCase()):[]);
  categoriesParDefaut.forEach(([nom,type])=>{if(!existantes.has(nom.toLowerCase())){categories.appendRow([Utilities.getUuid(),nom,type,'',true]);existantes.add(nom.toLowerCase());}});
  const parametres=ss.getSheetByName('Parametres');if(parametres.getLastRow()===1){parametres.appendRow(['version',BUDGETSOFT_VERSION]);parametres.appendRow(['devise','EUR']);parametres.appendRow(['locale','fr-FR']);}
}
function mettreAJourVersion_(){const feuille=SpreadsheetApp.getActiveSpreadsheet().getSheetByName('Parametres');if(!feuille||feuille.getLastRow()<2)return;const valeurs=feuille.getRange(2,1,feuille.getLastRow()-1,2).getValues(),index=valeurs.findIndex(l=>String(l[0]).trim()==='version');if(index>=0)feuille.getRange(index+2,2).setValue(BUDGETSOFT_VERSION);else feuille.appendRow(['version',BUDGETSOFT_VERSION]);}
function verifierInitialisation_(){const ss=SpreadsheetApp.getActiveSpreadsheet(),manquantes=Object.keys(TABLES).filter(n=>!ss.getSheetByName(n));if(manquantes.length)throw new Error('BudgetSoft n’est pas à jour. Lancez initialiserBudgetSoft(). Onglets manquants : '+manquantes.join(', '));}
function verifierNomTable_(nom){if(!Object.prototype.hasOwnProperty.call(TABLES,nom))throw new Error('Table inconnue : '+nom);}
function convertirNombre_(valeur){const n=Number(String(valeur==null?0:valeur).replace(/€/g,'').replace(/\s/g,'').replace(',','.'));if(!Number.isFinite(n))throw new Error('Le montant est invalide.');return n;}
function convertirBooleen_(valeur){return valeur!==false&&String(valeur).toLowerCase()!=='false'&&String(valeur)!=='0';}
function normaliserValeur_(valeur){if(valeur===undefined||valeur===null)return'';if(typeof valeur==='object'&&!(valeur instanceof Date))return JSON.stringify(valeur);return valeur;}
function serialiserValeur_(valeur){return valeur instanceof Date?valeur.toISOString():valeur;}
