const MAINTENANCE_VERSION='3.4';
const AUDIT_GENERAL_VERSION='1.4-2026-09-05';

function chargerCentreMaintenance(){
  verifierInitialisation_();
  const ss=SpreadsheetApp.getActiveSpreadsheet(),noms=['Operations','Charges_fixes','Correspondances_bancaires','Rapprochements_a_valider'],compteurs={};
  noms.forEach(n=>{const f=ss.getSheetByName(n);compteurs[n]=f?Math.max(0,f.getLastRow()-1):0;});
  return{version:MAINTENANCE_VERSION,mode:'lecture_seule',doctrine:'Contrôle uniquement : aucune migration, réparation ou suppression automatique.',compteurs,controle:controlerQualiteBudgetSoft()};
}

function controlerQualiteBudgetSoft(){
  verifierInitialisation_();
  const comptes=lireTable_('Comptes')||[],categories=lireTable_('Categories')||[],operations=lireTable_('Operations')||[],charges=lireTable_('Charges_fixes')||[],anomalies=[];
  const compteIds=new Set(comptes.map(c=>String(c.id||''))),compteNoms=new Set(comptes.map(c=>normaliserTexteMaintenance_(c.nom))),catNoms=new Set(categories.map(c=>normaliserTexteMaintenance_(c.nom)));
  ajouterDoublonsNoms_(comptes,'nom','Compte en double',anomalies);ajouterDoublonsNoms_(categories,'nom','Catégorie en double',anomalies);
  operations.forEach((o,i)=>{
    const n=i+2,d=auditGeneralDate_(o.date_comptable||o.date),m=Number(o.montant),cp=String(o.compte||''),cat=String(o.categorie||'').trim();
    if(!String(o.id||'').trim())anomalies.push({niveau:'erreur',domaine:'Sources',message:'Ligne '+n+' : opération sans ID.'});
    if(!d)anomalies.push({niveau:'erreur',domaine:'Opérations',message:'Ligne '+n+' : date invalide.'});
    if(!Number.isFinite(m)||m===0)anomalies.push({niveau:'erreur',domaine:'Opérations',message:'Ligne '+n+' : montant nul ou invalide.'});
    if(cp&&!compteIds.has(cp)&&!compteNoms.has(normaliserTexteMaintenance_(cp)))anomalies.push({niveau:'erreur',domaine:'Comptes',message:'Ligne '+n+' : compte inconnu.'});
    if(!cat)anomalies.push({niveau:'attention',domaine:'Catégories',message:'Ligne '+n+' : opération sans catégorie.'});
    else if(!catNoms.has(normaliserTexteMaintenance_(cat)))anomalies.push({niveau:'attention',domaine:'Catégories',message:'Ligne '+n+' : catégorie inconnue « '+cat+' ».'});
  });
  const dup=auditGeneralDoublonsOperations_(operations);dup.exemplesForts.forEach(x=>anomalies.push({niveau:'attention',domaine:'Doublons',message:x}));
  charges.forEach((c,i)=>{if(!auditGeneralActif_(c.actif))return;const n=i+2,m=Number(c.montant||0),cat=String(c.categorie||'').trim();if(!Number.isFinite(m)||m<=0)anomalies.push({niveau:'attention',domaine:'Charges fixes',message:'Ligne '+n+' : charge active sans montant valide.'});if(cat&&!catNoms.has(normaliserTexteMaintenance_(cat)))anomalies.push({niveau:'attention',domaine:'Charges fixes',message:'Ligne '+n+' : catégorie inconnue « '+cat+' ».'});});
  const erreurs=anomalies.filter(a=>a.niveau==='erreur').length,attentions=anomalies.filter(a=>a.niveau==='attention').length;
  return{score:Math.max(0,Math.round(100-erreurs*8-attentions*2)),erreurs,attentions,anomalies,compteurs:{comptes:comptes.length,categories:categories.length,operations:operations.length,chargesFixesActives:charges.filter(c=>auditGeneralActif_(c.actif)).length}};
}

function auditerBudgetSoftGeneral(){
  verifierInitialisation_();
  const t0=Date.now(),controles=[],performances=[],tables={};
  ['Comptes','Categories','Operations','Charges_fixes','Credits','Dettes','Actifs'].forEach(n=>{try{tables[n]=lireTable_(n)||[];}catch(e){tables[n]=[];}});
  const comptes=tables.Comptes,categories=tables.Categories,operations=tables.Operations,charges=tables.Charges_fixes,credits=tables.Credits,dettes=tables.Dettes,actifs=tables.Actifs;
  const compteIds=new Set(comptes.map(c=>String(c.id||'')).filter(Boolean)),compteNoms=new Set(comptes.map(c=>normaliserTexteMaintenance_(c.nom)).filter(Boolean)),catNoms=new Set(categories.map(c=>normaliserTexteMaintenance_(c.nom)).filter(Boolean)),opIds=new Set(operations.map(o=>String(o.id||'')).filter(Boolean)),chargeIds=new Set(charges.map(c=>String(c.id||'')).filter(Boolean)),creditIds=new Set(credits.map(c=>String(c.id||'')).filter(Boolean)),detteIds=new Set(dettes.map(d=>String(d.id||'')).filter(Boolean));

  auditGeneralAjouter_(controles,'Sources','Operations présentes',operations.length?'ok':'attention',operations.length,null,'Nombre de mouvements réels présents dans le tableur.');
  const idsOps=auditGeneralEtatIds_(operations),idsComptes=auditGeneralEtatIds_(comptes),idsCharges=auditGeneralEtatIds_(charges);
  auditGeneralAjouter_(controles,'Sources','IDs Operations présents',idsOps.manquants?'erreur':'ok',idsOps.manquants,0,'Chaque opération doit avoir un identifiant non vide.',true);
  auditGeneralAjouter_(controles,'Sources','IDs Operations uniques',idsOps.doublons?'erreur':'ok',idsOps.doublons,0,'Aucun identifiant d’opération ne doit être réutilisé.',true);
  auditGeneralAjouter_(controles,'Sources','IDs Comptes présents',idsComptes.manquants?'erreur':'ok',idsComptes.manquants,0,'Chaque compte doit avoir un identifiant non vide.',true);
  auditGeneralAjouter_(controles,'Sources','IDs Comptes uniques',idsComptes.doublons?'erreur':'ok',idsComptes.doublons,0,'Aucun identifiant de compte ne doit être réutilisé.',true);
  auditGeneralAjouter_(controles,'Sources','IDs Charges fixes présents',idsCharges.manquants?'erreur':'ok',idsCharges.manquants,0,'Chaque charge fixe doit avoir un identifiant non vide.',true);
  auditGeneralAjouter_(controles,'Sources','IDs Charges fixes uniques',idsCharges.doublons?'erreur':'ok',idsCharges.doublons,0,'Aucun identifiant de charge fixe ne doit être réutilisé.',true);

  let datesInvalides=0,montantsInvalides=0,comptesInconnus=0,sansCategorie=0,nbCatsInconnuesOps=0;const catsInconnues=new Map();
  operations.forEach((o,i)=>{const d=auditGeneralDate_(o.date_comptable||o.date),m=Number(o.montant),cp=String(o.compte||''),cat=String(o.categorie||'').trim();if(!d)datesInvalides++;if(!Number.isFinite(m)||m===0)montantsInvalides++;if(cp&&!compteIds.has(cp)&&!compteNoms.has(normaliserTexteMaintenance_(cp)))comptesInconnus++;if(!cat)sansCategorie++;else if(!catNoms.has(normaliserTexteMaintenance_(cat))){nbCatsInconnuesOps++;const k=cat||'(vide)',g=catsInconnues.get(k)||{nombre:0,exemples:[]};g.nombre++;if(g.exemples.length<4)g.exemples.push(auditGeneralExempleOperation_(o,i));catsInconnues.set(k,g);}});
  auditGeneralAjouter_(controles,'Opérations','Dates valides',datesInvalides?'erreur':'ok',datesInvalides,0,'Opérations dont la date bancaire/comptable est invalide.',true);
  auditGeneralAjouter_(controles,'Opérations','Montants valides',montantsInvalides?'erreur':'ok',montantsInvalides,0,'Montants nuls, non numériques ou invalides.',true);
  auditGeneralAjouter_(controles,'Opérations','Comptes référencés',comptesInconnus?'erreur':'ok',comptesInconnus,0,'Opérations rattachées à un compte inconnu.',true);
  const detailCats=[...catsInconnues.entries()].map(([nom,g])=>'« '+nom+' » : '+g.nombre+' opération(s)'+(g.exemples.length?' — '+g.exemples.join(' ; '):'')).join(' | ');
  auditGeneralAjouter_(controles,'Opérations','Catégories connues',nbCatsInconnuesOps?'attention':'ok',nbCatsInconnuesOps,0,nbCatsInconnuesOps?'Opérations utilisant une catégorie absente du référentiel. '+detailCats:'Toutes les catégories utilisées existent dans le référentiel.');
  auditGeneralAjouter_(controles,'Opérations','Opérations à classer',sansCategorie?'attention':'ok',sansCategorie,0,'Opérations sans catégorie métier.');
  const doublons=auditGeneralDoublonsOperations_(operations);
  auditGeneralAjouter_(controles,'Opérations','Doublons forts',doublons.forts?'attention':'ok',doublons.forts,0,doublons.forts?'Même opération apparente avec une référence bancaire/import identique. Exemples : '+doublons.exemplesForts.slice(0,5).join(' · '):'Aucun doublon fort : aucune collision n’est confirmée par une référence bancaire/import commune.');
  auditGeneralAjouter_(controles,'Opérations','Transactions similaires',doublons.similaires?'info':'ok',doublons.similaires,0,doublons.similaires?'Collisions date + compte + libellé + montant sans preuve suffisante de doublon. Exemples : '+doublons.exemplesSimilaires.slice(0,5).join(' · '):'Aucune transaction similaire détectée.');

  const comptesActifs=comptes.filter(c=>auditGeneralActif_(c.actif));
  const soldes=comptesActifs.map(c=>({id:String(c.id||''),nom:String(c.nom||''),type:String(c.type||'').toLowerCase(),solde:auditGeneralArrondi_(auditGeneralNombre_(c.solde_initial)+operations.filter(o=>String(o.compte||'')===String(c.id||'')||String(o.compte||'')===String(c.nom||'')).reduce((s,o)=>s+auditGeneralNombre_(o.montant),0))}));
  auditGeneralAjouter_(controles,'Comptes','Solde global reconstruit','info',auditGeneralArrondi_(soldes.reduce((s,c)=>s+c.solde,0)),null,'Solde initial + toutes les opérations rattachées aux comptes actifs.');
  auditGeneralAjouter_(controles,'Comptes','Épargne / placements reconstruits','info',auditGeneralArrondi_(soldes.filter(c=>['epargne','placement'].includes(c.type)).reduce((s,c)=>s+c.solde,0)),null,'Soldes reconstruits des comptes de type épargne ou placement.');

  const chargesActives=charges.filter(c=>auditGeneralActif_(c.actif)),totalChargesMensuel=auditGeneralArrondi_(chargesActives.reduce((s,c)=>s+auditGeneralMensualiserCharge_(c),0));
  auditGeneralAjouter_(controles,'Charges fixes','Charges actives source','info',chargesActives.length,null,'Nombre de références CF0 actives.');
  auditGeneralAjouter_(controles,'Charges fixes','Référence mensuelle source','info',totalChargesMensuel,null,'Mensualisation directe du référentiel Charges_fixes.');
  let liensCfInvalides=0;operations.forEach(o=>{const id=String(o.charge_fixe_id||'').trim();if(id&&!chargeIds.has(id))liensCfInvalides++;});
  auditGeneralAjouter_(controles,'Rapprochements','Liens opération → charge fixe',liensCfInvalides?'erreur':'ok',liensCfInvalides,0,'Toute charge_fixe_id d’une opération doit exister dans Charges_fixes.',true);

  auditGeneralChronometre_(performances,'Crédits / dettes',()=>{
    const m=typeof chargerCreditsEtDettesV2==='function'?chargerCreditsEtDettesV2():null;if(!m){auditGeneralAjouter_(controles,'Crédits','Moteur crédits disponible','erreur','indisponible','disponible','Moteur introuvable.',true);return;}
    const capC=auditGeneralArrondi_(credits.reduce((s,c)=>s+Math.max(0,auditGeneralNombre_(c.capital_restant)),0)),detAct=dettes.filter(d=>auditGeneralActif_(d.actif)&&auditGeneralNombre_(d.capital_restant)>0),capD=auditGeneralArrondi_(detAct.reduce((s,d)=>s+Math.max(0,auditGeneralNombre_(d.capital_restant)),0)),mensC=auditGeneralArrondi_(credits.reduce((s,c)=>s+Math.max(0,auditGeneralNombre_(c.mensualite)),0)),mensD=auditGeneralArrondi_(detAct.reduce((s,d)=>s+Math.max(0,auditGeneralNombre_(d.mensualite)),0));
    auditGeneralComparer_(controles,'Crédits','Capital crédits',capC,m.capitalCredits,.01,true);auditGeneralComparer_(controles,'Crédits','Dettes hors crédit actives',capD,m.dettesHorsCredit,.01,true);auditGeneralComparer_(controles,'Crédits','Endettement total',capC+capD,m.endettementTotal,.01,true);auditGeneralComparer_(controles,'Crédits','Mensualités totales',mensC+mensD,m.mensualites,.01,true);(m.alertes||[]).forEach(a=>auditGeneralAjouter_(controles,'Crédits',String(a.nom||'Financement'),a.niveau==='attention'?'attention':'info',a.message,null,'Contrôle propre au module Crédits.'));
  },controles);

  const opDette={};dettes.forEach(d=>String(d.operations_rapprochees||'').split(',').map(x=>x.trim()).filter(Boolean).forEach(id=>opDette[id]=(opDette[id]||0)+1));
  const opAbs=Object.keys(opDette).filter(id=>!opIds.has(id)).length,opDup=Object.values(opDette).filter(n=>n>1).length;
  auditGeneralAjouter_(controles,'Rapprochements','Paiements de dettes existants',opAbs?'erreur':'ok',opAbs,0,'Les IDs mémorisés dans Dettes doivent exister dans Operations.',true);auditGeneralAjouter_(controles,'Rapprochements','Paiement de dette utilisé une seule fois',opDup?'erreur':'ok',opDup,0,'Une même opération bancaire ne doit pas diminuer deux dettes.',true);

  auditGeneralChronometre_(performances,'Plan',()=>{
    const actions=typeof lireFeuilleDynamiquePlan_==='function'?(lireFeuilleDynamiquePlan_('Plan_Actions')||[]):[],objectifs=typeof lireTablePlanCerbere_==='function'?(lireTablePlanCerbere_('Plan_Objectifs')||[]):[],evenements=typeof lireFeuilleDynamiquePlan_==='function'?(lireFeuilleDynamiquePlan_('Plan_Evenements')||[]):[];
    const idsActions=auditGeneralEtatIds_(actions),idsObjectifs=auditGeneralEtatIds_(objectifs),idsEvenements=auditGeneralEtatIds_(evenements);
    auditGeneralAjouter_(controles,'Plan','IDs Actions présents',idsActions.manquants?'erreur':'ok',idsActions.manquants,0,'Chaque action du Plan doit avoir un ID.',true);
    auditGeneralAjouter_(controles,'Plan','IDs Actions uniques',idsActions.doublons?'erreur':'ok',idsActions.doublons,0,'Aucun ID d’action ne doit être réutilisé.',true);
    auditGeneralAjouter_(controles,'Plan','IDs Objectifs présents',idsObjectifs.manquants?'erreur':'ok',idsObjectifs.manquants,0,'Chaque objectif du Plan doit avoir un ID.',true);
    auditGeneralAjouter_(controles,'Plan','IDs Objectifs uniques',idsObjectifs.doublons?'erreur':'ok',idsObjectifs.doublons,0,'Aucun ID d’objectif ne doit être réutilisé.',true);
    auditGeneralAjouter_(controles,'Plan','IDs Événements présents',idsEvenements.manquants?'erreur':'ok',idsEvenements.manquants,0,'Chaque événement du Plan doit avoir un ID.',true);
    auditGeneralAjouter_(controles,'Plan','IDs Événements uniques',idsEvenements.doublons?'erreur':'ok',idsEvenements.doublons,0,'Aucun ID d’événement ne doit être réutilisé.',true);
    const objectifIds=new Set(objectifs.map(x=>String(x&&x.id||'').trim()).filter(Boolean)),orphelines=actions.filter(a=>{const id=String(a&&a.objectif_id||'').trim();return id&&!objectifIds.has(id);});
    auditGeneralAjouter_(controles,'Plan','Actions → objectifs',orphelines.length?'attention':'ok',orphelines.length,0,orphelines.length?'Actions rattachées à un objectif inexistant : '+orphelines.slice(0,6).map(a=>String(a.libelle||a.id||'action')+' → '+String(a.objectif_id)).join(' · '):'Toutes les actions rattachées à un objectif pointent vers un objectif existant.');
    const refsOps=[];actions.forEach(a=>{const id=String(a&&a.operation_reelle_id||'').trim();if(id&&!opIds.has(id))refsOps.push('Action '+String(a.libelle||a.id||'')+' → '+id);});evenements.forEach(e=>{const id=String(e&&e.operation_reelle_id||'').trim();if(id&&!opIds.has(id))refsOps.push('Événement '+String(e.libelle||e.id||'')+' → '+id);});
    auditGeneralAjouter_(controles,'Plan','Opérations réelles référencées',refsOps.length?'attention':'ok',refsOps.length,0,refsOps.length?'Références vers des opérations absentes : '+refsOps.slice(0,6).join(' · '):'Toutes les opérations réelles mémorisées dans le Plan existent.');
    const refsSources=[];actions.forEach(a=>{const type=normaliserTexteMaintenance_(a&&a.source_type),id=String(a&&a.source_id||'').trim();if(!id)return;let ok=true;if(type==='charge_fixe'||type==='charge fixe')ok=chargeIds.has(id);else if(type==='credit'||type==='crédit')ok=creditIds.has(id);else if(type==='dette')ok=detteIds.has(id);else if(type==='operation'||type==='opération')ok=opIds.has(id);if(!ok)refsSources.push(String(a.libelle||a.id||'action')+' · '+String(a.source_type||'source')+' '+id);});
    auditGeneralAjouter_(controles,'Plan','Sources des actions référencées',refsSources.length?'attention':'ok',refsSources.length,0,refsSources.length?'Sources devenues introuvables : '+refsSources.slice(0,6).join(' · '):'Les sources typées des actions pointent vers des objets existants.');
    if(typeof chargerPlanStructureV54==='function'){
      const s=chargerPlanStructureV54();
      auditGeneralComparer_(controles,'Plan','V5.4 · nombre d’actions',actions.length,(s.actions||[]).length,0,false,'La structure V5.4 doit exposer toutes les actions source.');
      auditGeneralComparer_(controles,'Plan','V5.4 · nombre d’objectifs',objectifs.length,(s.objectifs||[]).length,0,false,'La structure V5.4 doit exposer tous les objectifs source.');
      auditGeneralComparer_(controles,'Plan','V5.4 · nombre d’événements',evenements.length,(s.evenements||[]).length,0,false,'La structure V5.4 doit exposer tous les événements source.');
      const ga=s.gains_attendus||{};auditGeneralAjouter_(controles,'Plan','V5.4 · gains attendus','info','mensuel '+auditGeneralArrondi_(auditGeneralNombre_(ga.mensuel))+' € · annuel '+auditGeneralArrondi_(auditGeneralNombre_(ga.annuel))+' €',null,'Valeurs calculées par le moteur Plan V5.4.');
    }
    if(typeof chargerMesuresPlanV54==='function'){
      const m=chargerMesuresPlanV54(),mesures=m&&m.mesures||{},nbMesures=Object.keys(mesures).length;
      auditGeneralComparer_(controles,'Plan','V5.4 · actions mesurées',actions.length,nbMesures,0,false,'Chaque action doit disposer d’une entrée de mesure V5.4.');
      const ge=m.gains_effectifs||{};auditGeneralAjouter_(controles,'Plan','V5.4 · gains effectifs','info','mensuel '+auditGeneralArrondi_(auditGeneralNombre_(ge.mensuel))+' € · annuel '+auditGeneralArrondi_(auditGeneralNombre_(ge.annuel))+' €',null,'Valeurs mesurées par le moteur Plan V5.4.');
    }
  },controles);

  let rapprochementsCf=[];try{rapprochementsCf=lireTable_('Rapprochements_charges_fixes')||[];}catch(e){rapprochementsCf=[];}
  if(rapprochementsCf.length){
    const idsRcf=auditGeneralEtatIds_(rapprochementsCf);auditGeneralAjouter_(controles,'Rapprochements CF','IDs présents',idsRcf.manquants?'erreur':'ok',idsRcf.manquants,0,'Chaque rapprochement CF doit avoir un ID.',true);auditGeneralAjouter_(controles,'Rapprochements CF','IDs uniques',idsRcf.doublons?'erreur':'ok',idsRcf.doublons,0,'Aucun rapprochement CF ne doit partager le même ID.',true);
    let chargeAbs=0,opAbsCf=0,pairesDup=0,enAttente=0;const paires=new Set();rapprochementsCf.forEach(r=>{const cf=String(r&&r.charge_fixe_id||'').trim(),op=String(r&&r.operation_id||'').trim(),statut=String(r&&r.statut||'').trim();if(cf&&!chargeIds.has(cf))chargeAbs++;if(op&&!opIds.has(op))opAbsCf++;if(statut==='À valider')enAttente++;if(cf&&op){const k=cf+'|'+op;if(paires.has(k))pairesDup++;else paires.add(k);}});
    auditGeneralAjouter_(controles,'Rapprochements CF','Charges fixes référencées',chargeAbs?'attention':'ok',chargeAbs,0,'Chaque charge_fixe_id de la table de rapprochement doit encore exister.');auditGeneralAjouter_(controles,'Rapprochements CF','Opérations référencées',opAbsCf?'attention':'ok',opAbsCf,0,'Chaque operation_id de la table de rapprochement doit encore exister.');auditGeneralAjouter_(controles,'Rapprochements CF','Paires charge/opération uniques',pairesDup?'attention':'ok',pairesDup,0,'Une même paire charge fixe / opération ne devrait pas être enregistrée plusieurs fois.');auditGeneralAjouter_(controles,'Rapprochements CF','Propositions à valider','info',enAttente,null,'File de travail : ces propositions n’abaissent pas le score.');
  }else auditGeneralAjouter_(controles,'Rapprochements CF','Table disponible','info',0,null,'Aucun rapprochement de charge fixe enregistré.');
  let rapprochementsGeneraux=[];try{rapprochementsGeneraux=lireTable_('Rapprochements_a_valider')||[];}catch(e){rapprochementsGeneraux=[];}const attenteGenerale=rapprochementsGeneraux.filter(r=>String(r&&r.statut||'').trim()==='À valider').length;auditGeneralAjouter_(controles,'Rapprochements','Propositions bancaires à valider','info',attenteGenerale,null,'File de travail : les propositions en attente ne pénalisent pas la qualité des données.');

  auditGeneralChronometre_(performances,'Patrimoine',()=>{
    if(typeof chargerPatrimoine!=='function'){auditGeneralAjouter_(controles,'Patrimoine','Moteur patrimoine disponible','erreur','indisponible','disponible','Moteur introuvable.',true);return;}const p=chargerPatrimoine(),a=auditGeneralArrondi_(actifs.reduce((s,x)=>s+Math.max(0,auditGeneralNombre_(x.valeur)),0)),l=auditGeneralArrondi_(soldes.filter(c=>c.type==='epargne').reduce((s,c)=>s+Math.max(0,c.solde),0)),pl=auditGeneralArrondi_(soldes.filter(c=>c.type==='placement').reduce((s,c)=>s+Math.max(0,c.solde),0));auditGeneralComparer_(controles,'Patrimoine','Actifs patrimoniaux',a,p.totalActifsPatrimoniaux,.01,true);auditGeneralComparer_(controles,'Patrimoine','Livrets',l,p.totalLivrets,.01,true);auditGeneralComparer_(controles,'Patrimoine','Placements',pl,p.totalPlacements,.01,true);auditGeneralComparer_(controles,'Patrimoine','Total actifs',a+l+pl,p.totalActifs,.01,true);
  },controles);

  auditGeneralChronometre_(performances,'Analyses',()=>{
    if(typeof chargerAnalysesBudgetairesV23!=='function'){auditGeneralAjouter_(controles,'Analyses','Moteur disponible','erreur','indisponible','disponible','Moteur introuvable.',true);return;}const a=chargerAnalysesBudgetairesV23(6),ps=Array.isArray(a.periodes)?a.periodes:[],cour=a.courante||ps[ps.length-1]||{},dd=auditGeneralDate_(cour.debut),df=auditGeneralDate_(cour.fin);auditGeneralAjouter_(controles,'Analyses','Cycle courant 28 → 27',dd&&df&&dd.getDate()===28&&df.getDate()===27?'ok':'erreur',dd&&df?auditGeneralDateIso_(dd)+' → '+auditGeneralDateIso_(df):'invalide','28 → 27','Frontière canonique des analyses.',true);
    const fr=((a.recettes||{}).fenetres||{})['6']||((a.recettes||{}).fenetres||{})[6]||{},sumS=auditGeneralArrondi_((fr.sources||[]).reduce((s,x)=>s+auditGeneralNombre_(x.montant),0)),prod=fr.producteurs||{},sumP=auditGeneralArrondi_(Object.keys(prod).reduce((s,k)=>s+auditGeneralNombre_(prod[k]),0));auditGeneralComparer_(controles,'Analyses','Revenus = somme des sources',sumS,fr.revenusEconomiques,.01,true);auditGeneralComparer_(controles,'Analyses','Revenus = somme des producteurs',sumP,fr.revenusEconomiques,.01,true);
    const completes=ps.filter(p=>p&&p.periodeComplete!==false);if(completes.length&&cour.periodeComplete===false){const moy=auditGeneralArrondi_(completes.reduce((s,p)=>s+auditGeneralNombre_(p.revenus),0)/completes.length);auditGeneralComparer_(controles,'Analyses','Moyenne recettes sur cycles complets',moy,fr.moyenneMensuelle,.01,false,'Une période courante incomplète ne doit pas abaisser la moyenne affichée.');}
    const dep=a.depensesDetail||{},fd=(dep.fenetres||{})['6']||(dep.fenetres||{})[6]||{},alim=fd.alimentation||{},sante=fd.sante||{};auditGeneralComparer_(controles,'Analyses','Charges fixes actives',chargesActives.length,dep.fixes&&dep.fixes.nombre,0,true);auditGeneralComparer_(controles,'Analyses','Charges fixes mensuelles',totalChargesMensuel,dep.fixes&&dep.fixes.montantMensuelReference,.02,true);auditGeneralComparer_(controles,'Analyses','Santé nette',auditGeneralNombre_(sante.soinsBruts)+auditGeneralNombre_(sante.couvertureMntAudiens)-auditGeneralNombre_(sante.remboursements),sante.coutNet,.01,true);auditGeneralComparer_(controles,'Analyses','Courses banque + Pluxee',auditGeneralNombre_(alim.coursesBanque)+auditGeneralNombre_(alim.pluxeeCourses),alim.coursesReelles,.01,true);auditGeneralComparer_(controles,'Analyses','Restaurants banque + Pluxee',auditGeneralNombre_(alim.restaurantsBanque)+auditGeneralNombre_(alim.pluxeeRestaurants),alim.restaurantsReels,.01,true);auditGeneralComparer_(controles,'Analyses','Total alimentation réelle',auditGeneralNombre_(alim.coursesReelles)+auditGeneralNombre_(alim.restaurantsReels),alim.totalReel,.01,true);const fin=fd.financement||{};if(Object.keys(fin).length)auditGeneralComparer_(controles,'Analyses','Désendettement net estimé',auditGeneralNombre_(fin.capitalRembourseEstime)-auditGeneralNombre_(fin.reinjectionsTresorerie),fin.desendettementNetEstime,.01,true);
  },controles);

  auditGeneralChronometre_(performances,'Cerbère',()=>{
    if(typeof chargerCerbereCockpit20260902!=='function'){auditGeneralAjouter_(controles,'Cerbère','Cockpit disponible','erreur','indisponible','disponible','Moteur introuvable.',true);return;}
    const tc=Date.now(),c=chargerCerbereCockpit20260902(),cockpitMs=Date.now()-tc;
    if(!c||c.ok===false){auditGeneralAjouter_(controles,'Cerbère','Cockpit calculable','erreur',c&&c.erreur||'échec','ok','Le cockpit maître doit pouvoir être calculé.',true);return;}
    auditGeneralProfilCerbere_(controles,performances,c,cockpitMs);
    (c.periodes||[]).slice(0,2).forEach((p,i)=>{const lib='C'+(i+1),env=Array.isArray(p.enveloppes)?p.enveloppes:[],v=p.v37||{},cp=v.cockpit20260902||{},prev=auditGeneralArrondi_(env.reduce((s,x)=>s+Math.max(0,auditGeneralNombre_(x.prevu)),0)),reel=auditGeneralArrondi_(env.reduce((s,x)=>s+Math.max(0,auditGeneralNombre_(x.reelNetPrevisionnel!=null?x.reelNetPrevisionnel:x.reelImpute)),0)),dpt=auditGeneralArrondi_(env.reduce((s,x)=>{const r=Math.max(0,auditGeneralNombre_(x.reelNetPrevisionnel!=null?x.reelNetPrevisionnel:x.reelImpute)),pl=Math.max(0,auditGeneralNombre_(x.planifie)),pr=Math.max(0,auditGeneralNombre_(x.prevu));return s+Math.max(pr,r+pl);},0));auditGeneralComparer_(controles,'Cerbère',lib+' · molettes = budget réparti',prev,cp.budgetRepartiMolettes,.02,true);auditGeneralComparer_(controles,'Cerbère',lib+' · reste P1',auditGeneralNombre_(cp.p1Total)-reel,cp.ret1,.02,true);auditGeneralComparer_(controles,'Cerbère',lib+' · marge à répartir',auditGeneralNombre_(cp.p1Total)-prev,cp.margeARepartir,.02,true);auditGeneralComparer_(controles,'Cerbère',lib+' · DPt1',dpt,cp.dpt1,.02,true);auditGeneralComparer_(controles,'Cerbère',lib+' · surplus vs P0',auditGeneralNombre_(cp.p1Total)-auditGeneralNombre_(cp.p0Total),cp.surplusVsP0,.02,true);const pd=auditGeneralDate_(p.periode&&p.periode.debut),pf=auditGeneralDate_(p.periode&&p.periode.fin);auditGeneralAjouter_(controles,'Cerbère',lib+' · frontière 28 → 27',pd&&pf&&pd.getDate()===28&&pf.getDate()===27?'ok':'erreur',pd&&pf?auditGeneralDateIso_(pd)+' → '+auditGeneralDateIso_(pf):'invalide','28 → 27','Le cockpit doit respecter la frontière canonique.',true);});if(c.cf0&&c.cf0.nombreActives!=null)auditGeneralComparer_(controles,'Cerbère','CF0 · nombre de charges actives',chargesActives.length,c.cf0.nombreActives,0,false,'Écart possible seulement si CF0 applique explicitement un périmètre différent.');
  },controles);

  auditGeneralChronometre_(performances,'Pluxee',()=>{if(typeof chargerPluxeeCerbere20260827!=='function')return;const p=chargerPluxeeCerbere20260827();if(!p||p.ok===false){auditGeneralAjouter_(controles,'Pluxee','Moteur Pluxee Cerbère','attention',p&&p.erreur||'indisponible','ok','Le contrôle Pluxee n’a pas pu être calculé.');return;}const al=p.allocation||{},env=auditGeneralNombre_(p.enveloppe);auditGeneralComparer_(controles,'Pluxee','Allocation Courses + Restaurants',auditGeneralNombre_(al.Courses)+auditGeneralNombre_(al.Restaurants),env,.01,true);if(p.reelParCategorie){const rt=Object.keys(p.reelParCategorie).reduce((s,k)=>s+Math.max(0,auditGeneralNombre_(p.reelParCategorie[k])),0);auditGeneralComparer_(controles,'Pluxee','Solde théorique',env-rt,p.soldeTheorique,.02,false,'Le reliquat antérieur peut expliquer un écart avec le solde réel, pas avec le solde théorique.');}},controles);

  performances.forEach(p=>{if(p.ms>15000&&p.module==='Cerbère')auditGeneralAjouter_(controles,'Performance',p.module,'attention',p.ms+' ms','≤ 15000 ms','Moteur lent pendant cet audit manuel.');});
  const erreurs=controles.filter(x=>x.niveau==='erreur').length,attentions=controles.filter(x=>x.niveau==='attention').length,oks=controles.filter(x=>x.niveau==='ok').length,bloquants=controles.filter(x=>x.niveau==='erreur'&&x.bloquant).length;
  return{version:AUDIT_GENERAL_VERSION,maintenanceVersion:MAINTENANCE_VERSION,genereLe:Utilities.formatDate(new Date(),Session.getScriptTimeZone()||'Europe/Paris','dd/MM/yyyy HH:mm:ss'),dureeMs:Date.now()-t0,statut:bloquants?'erreur':erreurs||attentions?'attention':'ok',score:Math.max(0,Math.round(100-erreurs*8-attentions*2)),synthese:{controles:controles.length,oks,attentions,erreurs,bloquants},compteurs:{operations:operations.length,comptes:comptes.length,categories:categories.length,chargesFixes:charges.length,credits:credits.length,dettes:dettes.length,actifs:actifs.length},performances,controles};
}

function auditGeneralProfilCerbere_(controles,performances,c,cockpitMs){
  const d=c&&c.diagnostic||{},t=d.timings&&typeof d.timings==='object'?d.timings:{},socle=Number(d.duree_ms),socleMs=Number.isFinite(socle)?Math.max(0,Math.round(socle)):null;
  if(socleMs!==null){
    auditGeneralAjouter_(controles,'Performance Cerbère','Socle Cerbère 3.5','info',socleMs+' ms',null,'Temps interne de chargerCerbereV33().');
    performances.push({module:'Cerbère · socle 3.5',ms:socleMs});
    const apres=Math.max(0,Math.round(Number(cockpitMs||0)-socleMs));
    auditGeneralAjouter_(controles,'Performance Cerbère','Couches après 3.5 + cockpit','info',apres+' ms',null,'Temps résiduel : Rolling/V37/audits/rapprochements/frontières/stabilisations/cockpit.');
    performances.push({module:'Cerbère · après 3.5',ms:apres});
  }
  const labels={initialisation_ms:'3.5 · initialisation',canons_ms:'3.5 · canons P0/R0',lecture_structure_ms:'3.5 · lecture structure',lecture_plan_ms:'3.5 · lecture Plan',indexation_ms:'3.5 · indexation',reel_leger_ms:'3.5 · réel léger',construction_periodes_ms:'3.5 · construction P1–P6'};
  Object.keys(labels).forEach(k=>{const ms=Number(t[k]);if(!Number.isFinite(ms))return;const n=Math.max(0,Math.round(ms));auditGeneralAjouter_(controles,'Performance Cerbère',labels[k],'info',n+' ms',null,'Chronométrage interne du socle 3.5.');performances.push({module:'Cerbère · '+labels[k],ms:n});});
  auditGeneralAjouter_(controles,'Performance Cerbère','Cockpit complet mesuré','info',Math.max(0,Math.round(Number(cockpitMs||0)))+' ms',null,'Temps mesuré autour de chargerCerbereCockpit20260902().');
}

function auditGeneralChronometre_(perf,module,fn,controles){const t=Date.now();try{fn();}catch(e){perf.push({module,ms:Date.now()-t,erreur:String(e&&e.message||e)});if(controles)auditGeneralAjouter_(controles,module,'Moteur calculable','erreur','échec','ok',String(e&&e.message||e),true);}finally{if(!perf.some(x=>x.module===module))perf.push({module,ms:Date.now()-t});}}
function auditGeneralAjouter_(arr,domaine,controle,niveau,source,module,message,bloquant){arr.push({domaine,controle,niveau:niveau||'info',source:auditGeneralValeur_(source),module:auditGeneralValeur_(module),ecart:null,message:message||'',bloquant:!!bloquant});}
function auditGeneralComparer_(arr,domaine,controle,source,module,tolerance,bloquant,message){const a=Number(source),b=Number(module),tol=Number(tolerance||0),valid=Number.isFinite(a)&&Number.isFinite(b),ecart=valid?auditGeneralArrondi_(b-a):null,niveau=valid&&Math.abs(ecart)<=tol?'ok':(bloquant?'erreur':'attention');arr.push({domaine,controle,niveau,source:auditGeneralValeur_(source),module:auditGeneralValeur_(module),ecart:auditGeneralValeur_(ecart),message:message||'Comparaison source brute ↔ moteur BudgetSoft.',bloquant:!!bloquant});}
function auditGeneralValeur_(v){if(v===null||v===undefined||v==='')return null;if(typeof v==='number')return auditGeneralArrondi_(v);if(v instanceof Date)return auditGeneralDateIso_(v);return String(v);}
function auditGeneralNombre_(v){if(typeof convertirNombre_==='function')return convertirNombre_(v||0);const n=Number(String(v==null?'':v).replace(/\s/g,'').replace(',','.'));return Number.isFinite(n)?n:0;}
function auditGeneralArrondi_(n){n=Number(n);return Number.isFinite(n)?Math.round(n*100)/100:0;}
function auditGeneralActif_(v){if(typeof convertirBooleen_==='function')return convertirBooleen_(v);if(v===false||v===0||v===null||v===undefined)return false;return !['0','false','non','no','inactif','inactive'].includes(String(v).trim().toLowerCase());}
function auditGeneralDate_(v){if(!v)return null;const d=v instanceof Date?new Date(v):new Date(v);return isNaN(d.getTime())?null:d;}
function auditGeneralDateIso_(d){return Utilities.formatDate(d,Session.getScriptTimeZone()||'Europe/Paris','yyyy-MM-dd');}
function auditGeneralExempleOperation_(o,i){const d=auditGeneralDate_(o&&o.date_comptable||o&&o.date),date=d?auditGeneralDateIso_(d):'date ?',lib=String(o&&o.libelle||o&&o.libelle_bancaire||'').slice(0,40),m=Math.abs(auditGeneralNombre_(o&&o.montant));return 'ligne '+(Number(i)+2)+' · '+date+' · '+lib+' · '+m.toFixed(2)+' €';}
function auditGeneralEtatIds_(lignes){const ids=(lignes||[]).map(x=>String(x&&x.id||'').trim()),manquants=ids.filter(x=>!x).length,comptes={};ids.filter(Boolean).forEach(id=>comptes[id]=(comptes[id]||0)+1);const doublons=Object.keys(comptes).reduce((s,id)=>s+Math.max(0,comptes[id]-1),0);return{manquants,doublons,total:ids.length};}
function auditGeneralIdsUniques_(lignes){const e=auditGeneralEtatIds_(lignes);return e.manquants===0&&e.doublons===0;}
function auditGeneralMensualiserCharge_(c){const m=Math.abs(auditGeneralNombre_(c&&c.montant)),f=normaliserTexteMaintenance_(c&&c.frequence);if(f.indexOf('annu')>=0)return m/12;if(f.indexOf('trimes')>=0)return m/3;if(f.indexOf('semestr')>=0)return m/6;if(f.indexOf('bimes')>=0)return m/2;if(f.indexOf('hebdo')>=0)return m*52/12;if(f.indexOf('quotid')>=0)return m*365/12;return m;}
function auditGeneralReferenceForteOperation_(o){const champs=['cle_rapprochement','reference_bancaire','reference_operation','id_bancaire','transaction_id','operation_bancaire_id','empreinte_import','hash_import','source_id','id_source'];for(let i=0;i<champs.length;i++){const k=champs[i],v=String(o&&o[k]||'').trim();if(v)return k+'='+v;}const source=String(o&&o.source_bancaire||'').trim(),ligne=String(o&&(o.source_ligne||o.ligne_source||o.numero_ligne_source)||'').trim();return source&&ligne?'source_ligne='+source+'|'+ligne:'';}
function auditGeneralDoublonsOperations_(ops){const groupes=new Map(),exemplesForts=[],exemplesSimilaires=[];let forts=0,similaires=0;(ops||[]).forEach((o,i)=>{const d=auditGeneralDate_(o.date_comptable||o.date),date=d?auditGeneralDateIso_(d):'',lib=normaliserTexteMaintenance_(o.libelle_bancaire||o.libelle),mont=Math.abs(auditGeneralNombre_(o.montant)),cp=String(o.compte||''),k=[date,lib,mont.toFixed(2),cp].join('|'),precedents=groupes.get(k)||[],ref=auditGeneralReferenceForteOperation_(o),fort=ref&&precedents.some(x=>x.ref===ref),texte='lignes '+((precedents.length?precedents[0].i:i)+2)+' / '+(i+2)+' · '+date+' · '+String(o.libelle||o.libelle_bancaire||'').slice(0,45)+' · '+mont.toFixed(2)+' €';if(precedents.length){if(fort){forts++;if(exemplesForts.length<8)exemplesForts.push(texte+' · référence '+ref);}else{similaires++;if(exemplesSimilaires.length<8)exemplesSimilaires.push(texte);}}precedents.push({i,ref});groupes.set(k,precedents);});return{nombre:forts,forts,similaires,exemples:exemplesForts,exemplesForts,exemplesSimilaires};}
function ajouterDoublonsNoms_(lignes,champ,libelle,anomalies){const vus={};(lignes||[]).forEach((l,i)=>{const k=normaliserTexteMaintenance_(l[champ]);if(!k)return;if(vus[k])anomalies.push({niveau:'attention',domaine:'Doublons',message:libelle+' : lignes '+vus[k]+' et '+(i+2)+'.'});else vus[k]=i+2;});}
function normaliserTexteMaintenance_(v){return String(v||'').trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');}
