const MAINTENANCE_VERSION='3.1';
const AUDIT_GENERAL_VERSION='1.1-2026-09-04';

function chargerCentreMaintenance(){
  verifierInitialisation_();
  const ss=SpreadsheetApp.getActiveSpreadsheet(),noms=['Operations','Charges_fixes','Correspondances_bancaires','Rapprochements_a_valider'],compteurs={};
  noms.forEach(n=>{const f=ss.getSheetByName(n);compteurs[n]=f?Math.max(0,f.getLastRow()-1):0;});
  return{version:MAINTENANCE_VERSION,mode:'lecture_seule',doctrine:'Contrôle uniquement : aucune migration, réparation ou suppression automatique.',compteurs,controle:controlerQualiteBudgetSoft()};
}

function controlerQualiteBudgetSoft(){
  verifierInitialisation_();
  const comptes=lireTable_('Comptes')||[],categories=lireTable_('Categories')||[],operations=lireTable_('Operations')||[],charges=lireTable_('Charges_fixes')||[],anomalies=[];
  const compteIds=new Set(comptes.map(c=>String(c.id||''))),compteNoms=new Set(comptes.map(c=>normaliserTexteMaintenance_(c.nom))),catNoms=new Set(categories.map(c=>normaliserTexteMaintenance_(c.nom)));
  ajouterDoublonsNoms_(comptes,'nom','Compte en double',anomalies);ajouterDoublonsNoms_(categories,'nom','Catégorie en double',anomalies);
  operations.forEach((o,i)=>{
    const n=i+2,d=auditGeneralDate_(o.date_comptable||o.date),m=Number(o.montant),cp=String(o.compte||''),cat=String(o.categorie||'').trim();
    if(!d)anomalies.push({niveau:'erreur',domaine:'Opérations',message:'Ligne '+n+' : date invalide.'});
    if(!Number.isFinite(m)||m===0)anomalies.push({niveau:'erreur',domaine:'Opérations',message:'Ligne '+n+' : montant nul ou invalide.'});
    if(cp&&!compteIds.has(cp)&&!compteNoms.has(normaliserTexteMaintenance_(cp)))anomalies.push({niveau:'erreur',domaine:'Comptes',message:'Ligne '+n+' : compte inconnu.'});
    if(!cat)anomalies.push({niveau:'attention',domaine:'Catégories',message:'Ligne '+n+' : opération sans catégorie.'});
    else if(!catNoms.has(normaliserTexteMaintenance_(cat)))anomalies.push({niveau:'attention',domaine:'Catégories',message:'Ligne '+n+' : catégorie inconnue « '+cat+' ».'});
  });
  const dup=auditGeneralDoublonsOperations_(operations);dup.exemples.forEach(x=>anomalies.push({niveau:'attention',domaine:'Doublons',message:x}));
  charges.forEach((c,i)=>{if(!auditGeneralActif_(c.actif))return;const n=i+2,m=Number(c.montant||0),cat=String(c.categorie||'').trim();if(!Number.isFinite(m)||m<=0)anomalies.push({niveau:'attention',domaine:'Charges fixes',message:'Ligne '+n+' : charge active sans montant valide.'});if(cat&&!catNoms.has(normaliserTexteMaintenance_(cat)))anomalies.push({niveau:'attention',domaine:'Charges fixes',message:'Ligne '+n+' : catégorie inconnue « '+cat+' ».'});});
  const erreurs=anomalies.filter(a=>a.niveau==='erreur').length,attentions=anomalies.filter(a=>a.niveau==='attention').length;
  return{score:Math.max(0,Math.round(100-erreurs*8-attentions*2)),erreurs,attentions,anomalies,compteurs:{comptes:comptes.length,categories:categories.length,operations:operations.length,chargesFixesActives:charges.filter(c=>auditGeneralActif_(c.actif)).length}};
}

function auditerBudgetSoftGeneral(){
  verifierInitialisation_();
  const t0=Date.now(),controles=[],performances=[],tables={};
  ['Comptes','Categories','Operations','Charges_fixes','Credits','Dettes','Actifs'].forEach(n=>{try{tables[n]=lireTable_(n)||[];}catch(e){tables[n]=[];}});
  const comptes=tables.Comptes,categories=tables.Categories,operations=tables.Operations,charges=tables.Charges_fixes,credits=tables.Credits,dettes=tables.Dettes,actifs=tables.Actifs;
  const compteIds=new Set(comptes.map(c=>String(c.id||'')).filter(Boolean)),compteNoms=new Set(comptes.map(c=>normaliserTexteMaintenance_(c.nom)).filter(Boolean)),catNoms=new Set(categories.map(c=>normaliserTexteMaintenance_(c.nom)).filter(Boolean)),opIds=new Set(operations.map(o=>String(o.id||'')).filter(Boolean)),chargeIds=new Set(charges.map(c=>String(c.id||'')).filter(Boolean));

  auditGeneralAjouter_(controles,'Sources','Operations présentes',operations.length?'ok':'attention',operations.length,null,'Nombre de mouvements réels présents dans le tableur.');
  auditGeneralAjouter_(controles,'Sources','IDs Operations uniques',auditGeneralIdsUniques_(operations)?'ok':'erreur',operations.length,null,'Chaque opération doit avoir un identifiant unique.',true);
  auditGeneralAjouter_(controles,'Sources','IDs Comptes uniques',auditGeneralIdsUniques_(comptes)?'ok':'erreur',comptes.length,null,'Chaque compte doit avoir un identifiant unique.',true);
  auditGeneralAjouter_(controles,'Sources','IDs Charges fixes uniques',auditGeneralIdsUniques_(charges)?'ok':'erreur',charges.length,null,'Chaque charge fixe doit avoir un identifiant unique.',true);

  let datesInvalides=0,montantsInvalides=0,comptesInconnus=0,sansCategorie=0;const catsInconnues=new Set();
  operations.forEach(o=>{const d=auditGeneralDate_(o.date_comptable||o.date),m=Number(o.montant),cp=String(o.compte||''),cat=String(o.categorie||'').trim();if(!d)datesInvalides++;if(!Number.isFinite(m)||m===0)montantsInvalides++;if(cp&&!compteIds.has(cp)&&!compteNoms.has(normaliserTexteMaintenance_(cp)))comptesInconnus++;if(!cat)sansCategorie++;else if(!catNoms.has(normaliserTexteMaintenance_(cat)))catsInconnues.add(cat);});
  auditGeneralAjouter_(controles,'Opérations','Dates valides',datesInvalides?'erreur':'ok',datesInvalides,0,'Opérations dont la date bancaire/comptable est invalide.',true);
  auditGeneralAjouter_(controles,'Opérations','Montants valides',montantsInvalides?'erreur':'ok',montantsInvalides,0,'Montants nuls, non numériques ou invalides.',true);
  auditGeneralAjouter_(controles,'Opérations','Comptes référencés',comptesInconnus?'erreur':'ok',comptesInconnus,0,'Opérations rattachées à un compte inconnu.',true);
  auditGeneralAjouter_(controles,'Opérations','Catégories connues',catsInconnues.size?'attention':'ok',catsInconnues.size,0,catsInconnues.size?'Catégories absentes du référentiel : '+[...catsInconnues].sort().join(', ')+'.':'Toutes les catégories utilisées existent dans le référentiel.');
  auditGeneralAjouter_(controles,'Opérations','Opérations à classer',sansCategorie?'attention':'ok',sansCategorie,0,'Opérations sans catégorie métier.');
  const doublons=auditGeneralDoublonsOperations_(operations);
  auditGeneralAjouter_(controles,'Opérations','Doublons probables',doublons.nombre?'attention':'ok',doublons.nombre,0,doublons.nombre?'Exemples : '+doublons.exemples.slice(0,5).join(' · '):'Aucun doublon probable selon la clé date + compte + libellé + montant.');

  const comptesActifs=comptes.filter(c=>auditGeneralActif_(c.actif));
  const soldes=comptesActifs.map(c=>({id:String(c.id||''),nom:String(c.nom||''),type:String(c.type||'').toLowerCase(),solde:auditGeneralArrondi_(auditGeneralNombre_(c.solde_initial)+operations.filter(o=>String(o.compte||'')===String(c.id||'')||String(o.compte||'')===String(c.nom||'')).reduce((s,o)=>s+auditGeneralNombre_(o.montant),0))}));
  auditGeneralAjouter_(controles,'Comptes','Solde global reconstruit','info',auditGeneralArrondi_(soldes.reduce((s,c)=>s+c.solde,0)),null,'Solde initial + toutes les opérations rattachées aux comptes actifs.');
  auditGeneralAjouter_(controles,'Comptes','Épargne / placements reconstruits','info',auditGeneralArrondi_(soldes.filter(c=>['epargne','placement'].includes(c.type)).reduce((s,c)=>s+c.solde,0)),null,'Soldes reconstruits des comptes de type épargne ou placement.');

  const chargesActives=charges.filter(c=>auditGeneralActif_(c.actif)),totalChargesMensuel=auditGeneralArrondi_(chargesActives.reduce((s,c)=>s+auditGeneralMensualiserCharge_(c),0));
  auditGeneralAjouter_(controles,'Charges fixes','Charges actives source','info',chargesActives.length,null,'Nombre de références CF0 actives.');
  auditGeneralAjouter_(controles,'Charges fixes','Référence mensuelle source','info',totalChargesMensuel,null,'Mensualisation directe du référentiel Charges_fixes.');
  let liensCfInvalides=0;operations.forEach(o=>{const id=String(o.charge_fixe_id||'').trim();if(id&&!chargeIds.has(id))liensCfInvalides++;});
  auditGeneralAjouter_(controles,'Rapprochements','Liens opération → charge fixe',liensCfInvalides?'erreur':'ok',liensCfInvalides,0,'Toute charge_fixe_id d’une opération doit exister dans Charges_fixes.',true);

  auditGeneralChronometre_(performances,'Crédits / dettes',()=>{
    const m=typeof chargerCreditsEtDettesV2==='function'?chargerCreditsEtDettesV2():null;if(!m){auditGeneralAjouter_(controles,'Crédits','Moteur crédits disponible','erreur','indisponible','disponible','Moteur introuvable.',true);return;}
    const capC=auditGeneralArrondi_(credits.reduce((s,c)=>s+Math.max(0,auditGeneralNombre_(c.capital_restant)),0)),detAct=dettes.filter(d=>auditGeneralActif_(d.actif)&&auditGeneralNombre_(d.capital_restant)>0),capD=auditGeneralArrondi_(detAct.reduce((s,d)=>s+Math.max(0,auditGeneralNombre_(d.capital_restant)),0)),mensC=auditGeneralArrondi_(credits.reduce((s,c)=>s+Math.max(0,auditGeneralNombre_(c.mensualite)),0)),mensD=auditGeneralArrondi_(detAct.reduce((s,d)=>s+Math.max(0,auditGeneralNombre_(d.mensualite)),0));
    auditGeneralComparer_(controles,'Crédits','Capital crédits',capC,m.capitalCredits,.01,true);auditGeneralComparer_(controles,'Crédits','Dettes hors crédit actives',capD,m.dettesHorsCredit,.01,true);auditGeneralComparer_(controles,'Crédits','Endettement total',capC+capD,m.endettementTotal,.01,true);auditGeneralComparer_(controles,'Crédits','Mensualités totales',mensC+mensD,m.mensualites,.01,true);(m.alertes||[]).forEach(a=>auditGeneralAjouter_(controles,'Crédits',String(a.nom||'Financement'),a.niveau==='attention'?'attention':'info',a.message,null,'Contrôle propre au module Crédits.'));
  },controles);

  const opDette={};dettes.forEach(d=>String(d.operations_rapprochees||'').split(',').map(x=>x.trim()).filter(Boolean).forEach(id=>opDette[id]=(opDette[id]||0)+1));
  const opAbs=Object.keys(opDette).filter(id=>!opIds.has(id)).length,opDup=Object.values(opDette).filter(n=>n>1).length;
  auditGeneralAjouter_(controles,'Rapprochements','Paiements de dettes existants',opAbs?'erreur':'ok',opAbs,0,'Les IDs mémorisés dans Dettes doivent exister dans Operations.',true);auditGeneralAjouter_(controles,'Rapprochements','Paiement de dette utilisé une seule fois',opDup?'erreur':'ok',opDup,0,'Une même opération bancaire ne doit pas diminuer deux dettes.',true);

  auditGeneralChronometre_(performances,'Patrimoine',()=>{
    if(typeof chargerPatrimoine!=='function'){auditGeneralAjouter_(controles,'Patrimoine','Moteur patrimoine disponible','erreur','indisponible','disponible','Moteur introuvable.',true);return;}const p=chargerPatrimoine(),a=auditGeneralArrondi_(actifs.reduce((s,x)=>s+Math.max(0,auditGeneralNombre_(x.valeur)),0)),l=auditGeneralArrondi_(soldes.filter(c=>c.type==='epargne').reduce((s,c)=>s+Math.max(0,c.solde),0)),pl=auditGeneralArrondi_(soldes.filter(c=>c.type==='placement').reduce((s,c)=>s+Math.max(0,c.solde),0));auditGeneralComparer_(controles,'Patrimoine','Actifs patrimoniaux',a,p.totalActifsPatrimoniaux,.01,true);auditGeneralComparer_(controles,'Patrimoine','Livrets',l,p.totalLivrets,.01,true);auditGeneralComparer_(controles,'Patrimoine','Placements',pl,p.totalPlacements,.01,true);auditGeneralComparer_(controles,'Patrimoine','Total actifs',a+l+pl,p.totalActifs,.01,true);
  },controles);

  auditGeneralChronometre_(performances,'Analyses',()=>{
    if(typeof chargerAnalysesBudgetairesV23!=='function'){auditGeneralAjouter_(controles,'Analyses','Moteur disponible','erreur','indisponible','disponible','Moteur introuvable.',true);return;}const a=chargerAnalysesBudgetairesV23(6),ps=Array.isArray(a.periodes)?a.periodes:[],cour=a.courante||ps[ps.length-1]||{},dd=auditGeneralDate_(cour.debut),df=auditGeneralDate_(cour.fin);auditGeneralAjouter_(controles,'Analyses','Cycle courant 28 → 27',dd&&df&&dd.getDate()===28&&df.getDate()===27?'ok':'erreur',dd&&df?auditGeneralDateIso_(dd)+' → '+auditGeneralDateIso_(df):'invalide','28 → 27','Frontière canonique des analyses.',true);
    const fr=((a.recettes||{}).fenetres||{})['6']||((a.recettes||{}).fenetres||{})[6]||{},sumS=auditGeneralArrondi_((fr.sources||[]).reduce((s,x)=>s+auditGeneralNombre_(x.montant),0)),prod=fr.producteurs||{},sumP=auditGeneralArrondi_(Object.keys(prod).reduce((s,k)=>s+auditGeneralNombre_(prod[k]),0));auditGeneralComparer_(controles,'Analyses','Revenus = somme des sources',sumS,fr.revenusEconomiques,.01,true);auditGeneralComparer_(controles,'Analyses','Revenus = somme des producteurs',sumP,fr.revenusEconomiques,.01,true);
    const completes=ps.filter(p=>p&&p.periodeComplete!==false);if(completes.length&&cour.periodeComplete===false){const moy=auditGeneralArrondi_(completes.reduce((s,p)=>s+auditGeneralNombre_(p.revenus),0)/completes.length);auditGeneralComparer_(controles,'Analyses','Moyenne recettes sur cycles complets',moy,fr.moyenneMensuelle,.01,false,'Une période courante incomplète ne doit pas abaisser la moyenne affichée.');}
    const dep=a.depensesDetail||{},fd=(dep.fenetres||{})['6']||(dep.fenetres||{})[6]||{},alim=fd.alimentation||{},sante=fd.sante||{};auditGeneralComparer_(controles,'Analyses','Charges fixes actives',chargesActives.length,dep.fixes&&dep.fixes.nombre,0,true);auditGeneralComparer_(controles,'Analyses','Charges fixes mensuelles',totalChargesMensuel,dep.fixes&&dep.fixes.montantMensuelReference,.02,true);auditGeneralComparer_(controles,'Analyses','Santé nette',auditGeneralNombre_(sante.soinsBruts)+auditGeneralNombre_(sante.couvertureMntAudiens)-auditGeneralNombre_(sante.remboursements),sante.coutNet,.01,true);auditGeneralComparer_(controles,'Analyses','Courses banque + Pluxee',auditGeneralNombre_(alim.coursesBanque)+auditGeneralNombre_(alim.pluxeeCourses),alim.coursesReelles,.01,true);auditGeneralComparer_(controles,'Analyses','Restaurants banque + Pluxee',auditGeneralNombre_(alim.restaurantsBanque)+auditGeneralNombre_(alim.pluxeeRestaurants),alim.restaurantsReels,.01,true);auditGeneralComparer_(controles,'Analyses','Total alimentation réelle',auditGeneralNombre_(alim.coursesReelles)+auditGeneralNombre_(alim.restaurantsReels),alim.totalReel,.01,true);const fin=fd.financement||{};if(Object.keys(fin).length)auditGeneralComparer_(controles,'Analyses','Désendettement net estimé',auditGeneralNombre_(fin.capitalRembourseEstime)-auditGeneralNombre_(fin.reinjectionsTresorerie),fin.desendettementNetEstime,.01,true);
  },controles);

  auditGeneralChronometre_(performances,'Cerbère',()=>{
    if(typeof chargerCerbereCockpit20260902!=='function'){auditGeneralAjouter_(controles,'Cerbère','Cockpit disponible','erreur','indisponible','disponible','Moteur introuvable.',true);return;}const c=chargerCerbereCockpit20260902();if(!c||c.ok===false){auditGeneralAjouter_(controles,'Cerbère','Cockpit calculable','erreur',c&&c.erreur||'échec','ok','Le cockpit maître doit pouvoir être calculé.',true);return;}(c.periodes||[]).slice(0,2).forEach((p,i)=>{const lib='C'+(i+1),env=Array.isArray(p.enveloppes)?p.enveloppes:[],v=p.v37||{},cp=v.cockpit20260902||{},prev=auditGeneralArrondi_(env.reduce((s,x)=>s+Math.max(0,auditGeneralNombre_(x.prevu)),0)),reel=auditGeneralArrondi_(env.reduce((s,x)=>s+Math.max(0,auditGeneralNombre_(x.reelNetPrevisionnel!=null?x.reelNetPrevisionnel:x.reelImpute)),0)),dpt=auditGeneralArrondi_(env.reduce((s,x)=>{const r=Math.max(0,auditGeneralNombre_(x.reelNetPrevisionnel!=null?x.reelNetPrevisionnel:x.reelImpute)),pl=Math.max(0,auditGeneralNombre_(x.planifie)),pr=Math.max(0,auditGeneralNombre_(x.prevu));return s+Math.max(pr,r+pl);},0));auditGeneralComparer_(controles,'Cerbère',lib+' · molettes = budget réparti',prev,cp.budgetRepartiMolettes,.02,true);auditGeneralComparer_(controles,'Cerbère',lib+' · reste P1',auditGeneralNombre_(cp.p1Total)-reel,cp.ret1,.02,true);auditGeneralComparer_(controles,'Cerbère',lib+' · marge à répartir',auditGeneralNombre_(cp.p1Total)-prev,cp.margeARepartir,.02,true);auditGeneralComparer_(controles,'Cerbère',lib+' · DPt1',dpt,cp.dpt1,.02,true);auditGeneralComparer_(controles,'Cerbère',lib+' · surplus vs P0',auditGeneralNombre_(cp.p1Total)-auditGeneralNombre_(cp.p0Total),cp.surplusVsP0,.02,true);const pd=auditGeneralDate_(p.periode&&p.periode.debut),pf=auditGeneralDate_(p.periode&&p.periode.fin);auditGeneralAjouter_(controles,'Cerbère',lib+' · frontière 28 → 27',pd&&pf&&pd.getDate()===28&&pf.getDate()===27?'ok':'erreur',pd&&pf?auditGeneralDateIso_(pd)+' → '+auditGeneralDateIso_(pf):'invalide','28 → 27','Le cockpit doit respecter la frontière canonique.',true);});if(c.cf0&&c.cf0.nombreActives!=null)auditGeneralComparer_(controles,'Cerbère','CF0 · nombre de charges actives',chargesActives.length,c.cf0.nombreActives,0,false,'Écart possible seulement si CF0 applique explicitement un périmètre différent.');
  },controles);

  auditGeneralChronometre_(performances,'Pluxee',()=>{if(typeof chargerPluxeeCerbere20260827!=='function')return;const p=chargerPluxeeCerbere20260827();if(!p||p.ok===false){auditGeneralAjouter_(controles,'Pluxee','Moteur Pluxee Cerbère','attention',p&&p.erreur||'indisponible','ok','Le contrôle Pluxee n’a pas pu être calculé.');return;}const al=p.allocation||{},env=auditGeneralNombre_(p.enveloppe);auditGeneralComparer_(controles,'Pluxee','Allocation Courses + Restaurants',auditGeneralNombre_(al.Courses)+auditGeneralNombre_(al.Restaurants),env,.01,true);if(p.reelParCategorie){const rt=Object.keys(p.reelParCategorie).reduce((s,k)=>s+Math.max(0,auditGeneralNombre_(p.reelParCategorie[k])),0);auditGeneralComparer_(controles,'Pluxee','Solde théorique',env-rt,p.soldeTheorique,.02,false,'Le reliquat antérieur peut expliquer un écart avec le solde réel, pas avec le solde théorique.');}},controles);

  performances.forEach(p=>{if(p.ms>15000)auditGeneralAjouter_(controles,'Performance',p.module,'attention',p.ms+' ms','≤ 15000 ms','Moteur lent pendant cet audit manuel.');});
  const erreurs=controles.filter(x=>x.niveau==='erreur').length,attentions=controles.filter(x=>x.niveau==='attention').length,oks=controles.filter(x=>x.niveau==='ok').length,bloquants=controles.filter(x=>x.niveau==='erreur'&&x.bloquant).length;
  return{version:AUDIT_GENERAL_VERSION,maintenanceVersion:MAINTENANCE_VERSION,genereLe:Utilities.formatDate(new Date(),Session.getScriptTimeZone()||'Europe/Paris','dd/MM/yyyy HH:mm:ss'),dureeMs:Date.now()-t0,statut:bloquants?'erreur':erreurs||attentions?'attention':'ok',score:Math.max(0,Math.round(100-erreurs*8-attentions*2)),synthese:{controles:controles.length,oks,attentions,erreurs,bloquants},compteurs:{operations:operations.length,comptes:comptes.length,categories:categories.length,chargesFixes:charges.length,credits:credits.length,dettes:dettes.length,actifs:actifs.length},performances,controles};
}

function auditGeneralChronometre_(perf,module,fn,controles){const t=Date.now();try{fn();}catch(e){perf.push({module,ms:Date.now()-t,erreur:String(e&&e.message||e)});if(controles)auditGeneralAjouter_(controles,module,'Moteur calculable','erreur','échec','ok',String(e&&e.message||e),true);}finally{if(!perf.some(x=>x.module===module))perf.push({module,ms:Date.now()-t});}}
function auditGeneralAjouter_(arr,domaine,controle,niveau,source,module,message,bloquant){arr.push({domaine,controle,niveau:niveau||'info',source:auditGeneralValeur_(source),module:auditGeneralValeur_(module),ecart:null,message:message||'',bloquant:!!bloquant});}
function auditGeneralComparer_(arr,domaine,controle,source,module,tolerance,bloquant,message){const a=Number(source),b=Number(module),tol=Number(tolerance||0),valid=Number.isFinite(a)&&Number.isFinite(b),ecart=valid?auditGeneralArrondi_(b-a):null,niveau=valid&&Math.abs(ecart)<=tol?'ok':(bloquant?'erreur':'attention');arr.push({domaine,controle,niveau,source:auditGeneralValeur_(source),module:auditGeneralValeur_(module),ecart:auditGeneralValeur_(ecart),message:message||'Comparaison source brute ↔ moteur BudgetSoft.',bloquant:!!bloquant});}
function auditGeneralValeur_(v){if(v===null||v===undefined||v==='')return null;if(typeof v==='number')return auditGeneralArrondi_(v);if(v instanceof Date)return auditGeneralDateIso_(v);return String(v);}
function auditGeneralNombre_(v){if(typeof convertirNombre_==='function')return convertirNombre_(v||0);const n=Number(String(v==null?'':v).replace(/\s/g,'').replace(',','.'));return Number.isFinite(n)?n:0;}
function auditGeneralArrondi_(n){n=Number(n);return Number.isFinite(n)?Math.round(n*100)/100:0;}
function auditGeneralActif_(v){if(typeof convertirBooleen_==='function')return convertirBooleen_(v);if(v===false||v===0||v===null||v===undefined)return false;return !['0','false','non','no','inactif','inactive'].includes(String(v).trim().toLowerCase());}
function auditGeneralDate_(v){if(!v)return null;const d=v instanceof Date?new Date(v):new Date(v);return isNaN(d.getTime())?null:d;}
function auditGeneralDateIso_(d){return Utilities.formatDate(d,Session.getScriptTimeZone()||'Europe/Paris','yyyy-MM-dd');}
function auditGeneralIdsUniques_(lignes){const ids=(lignes||[]).map(x=>String(x.id||'').trim()).filter(Boolean);return ids.length===new Set(ids).size;}
function auditGeneralMensualiserCharge_(c){const m=Math.abs(auditGeneralNombre_(c&&c.montant)),f=normaliserTexteMaintenance_(c&&c.frequence);if(f.indexOf('annu')>=0)return m/12;if(f.indexOf('trimes')>=0)return m/3;if(f.indexOf('semestr')>=0)return m/6;if(f.indexOf('bimes')>=0)return m/2;if(f.indexOf('hebdo')>=0)return m*52/12;if(f.indexOf('quotid')>=0)return m*365/12;return m;}
function auditGeneralDoublonsOperations_(ops){const vus=new Map(),exemples=[];let nombre=0;(ops||[]).forEach((o,i)=>{const d=auditGeneralDate_(o.date_comptable||o.date),date=d?auditGeneralDateIso_(d):'',lib=normaliserTexteMaintenance_(o.libelle_bancaire||o.libelle),mont=Math.abs(auditGeneralNombre_(o.montant)),cp=String(o.compte||''),k=[date,lib,mont.toFixed(2),cp].join('|');if(vus.has(k)){nombre++;if(exemples.length<8){const j=vus.get(k)+2;exemples.push('lignes '+j+' / '+(i+2)+' · '+date+' · '+String(o.libelle||o.libelle_bancaire||'').slice(0,45)+' · '+mont.toFixed(2)+' €');}}else vus.set(k,i);});return{nombre,exemples};}
function ajouterDoublonsNoms_(lignes,champ,libelle,anomalies){const vus={};(lignes||[]).forEach((l,i)=>{const k=normaliserTexteMaintenance_(l[champ]);if(!k)return;if(vus[k])anomalies.push({niveau:'attention',domaine:'Doublons',message:libelle+' : lignes '+vus[k]+' et '+(i+2)+'.'});else vus[k]=i+2;});}
function normaliserTexteMaintenance_(v){return String(v||'').trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');}
