const PLAN_ACTIONS_V4_VERSION='4.6.1';

function assurerColonnesPlanV4_(nom,extra){const sh=SpreadsheetApp.getActive().getSheetByName(nom);if(!sh)return;const hs=sh.getRange(1,1,1,sh.getLastColumn()).getValues()[0].map(x=>String(x||'').trim());const miss=extra.filter(x=>!hs.includes(x));if(miss.length)sh.getRange(1,hs.length+1,1,miss.length).setValues([miss]);}
function assurerPlanActionsV4_(){assurerPlanActionsV3_();assurerTablesPlanCerbere_();assurerColonnesPlanV4_('Plan_Actions',['nature_action','reevaluer_charges_fixes','categorie','source_remplacement_id','source_remplacement_libelle','mode_paiement','fractionne','nombre_fois','periodicite_fractionnement','dernier_recalcul']);assurerColonnesPlanV4_('Plan_Evenements',['categorie','recurrence','mode_paiement','fractionne','nombre_fois','periodicite_fractionnement','montant_reel','date_realisation','rapprochement_statut','operation_reelle_id','dernier_recalcul']);}
function listerCategoriesPlanV4(){let out=[];try{out=lireTable_('Categories').map(x=>String(x.nom||x.categorie||'').trim()).filter(Boolean);}catch(e){}if(!out.length){try{out=lireTablePlanCerbere_('Cerbere_Budget_Canonique').map(x=>String(x.categorie||'').trim()).filter(Boolean);}catch(e){}}out.push('Crédits');return [...new Set(out)].sort((a,b)=>a.localeCompare(b,'fr'));}
function chargerPlanActionsV4(){assurerPlanActionsV4_();const base=chargerActionsPlanV3(),objectifs=base.objectifs||[],actions=base.actions||[],evenements=lireFeuilleDynamiquePlan_('Plan_Evenements');const groupes=objectifs.map(o=>{const aa=actions.filter(a=>String(a.objectif_id||'')===String(o.id));return {objectif:o,actions:aa,impact:agregerImpactActionsV4_(aa)};});return serialiserCerberePourClient_({version:PLAN_ACTIONS_V4_VERSION,groupes,sansObjectif:actions.filter(a=>!a.objectif_id),actions,objectifs,versions:base.versions||[],gains:base.gains||{},evenements,categories:listerCategoriesPlanV4(),lignes_previsionnelles:construireLignesPrevisionnellesV4_(actions,evenements),projection:typeof etatProjectionBudgetSoft==='function'?etatProjectionBudgetSoft():null});}
function agregerImpactActionsV4_(actions){let attendu=0,acquis=0;(actions||[]).forEach(a=>{if(['Abandonnée','Annulée'].includes(String(a.statut)))return;const m=Math.abs(Number(a.impact_montant||0)),mensuel=String(a.impact_frequence)==='mensuel'?m:0;if(yesPlanV4_(a.impact_confirme))attendu+=mensuel;if(['Effective','Réalisée','Réalisé','Realisee','Realise'].includes(String(a.statut||'')))acquis+=mensuel;});return {mensuel_attendu:Math.round(attendu*100)/100,mensuel_acquis:Math.round(acquis*100)/100,annuel_attendu:Math.round(attendu*1200)/100,annuel_acquis:Math.round(acquis*1200)/100,mensuel_confirme:Math.round(attendu*100)/100,annuel_confirme:Math.round(attendu*1200)/100};}
function upsertDynamiquePlanV4_(nom,d){const sh=SpreadsheetApp.getActive().getSheetByName(nom),hs=sh.getRange(1,1,1,sh.getLastColumn()).getValues()[0].map(String),now=new Date().toISOString();if(!d.id)d.id=Utilities.getUuid();const old=lireFeuilleDynamiquePlan_(nom).find(x=>String(x.id)===String(d.id))||{};if(hs.includes('cree_le'))d.cree_le=old.cree_le||now;if(hs.includes('modifie_le'))d.modifie_le=now;const vals=hs.map(h=>normaliserValeur_(d[h]!==undefined?d[h]:old[h]));const ids=sh.getLastRow()>1?sh.getRange(2,1,sh.getLastRow()-1,1).getValues().flat():[],p=ids.findIndex(x=>String(x)===String(d.id));if(p>=0)sh.getRange(p+2,1,1,hs.length).setValues([vals]);else sh.appendRow(vals);return d;}
function normaliserFractionPlanV46_(d){d.mode_paiement=String(d.mode_paiement||'Virement');d.fractionne=yesPlanV4_(d.fractionne);d.nombre_fois=d.fractionne?Math.max(2,Math.min(36,Number(d.nombre_fois||2))):1;d.periodicite_fractionnement=d.fractionne?String(d.periodicite_fractionnement||'mensuel'):'ponctuel';return d;}
function enregistrerActionPlanV4(d){assurerPlanActionsV4_();d=Object.assign({},d||{});d.nature_action=String(d.nature_action||'autre');d.categorie=String(d.categorie||'').trim();d.reevaluer_charges_fixes=d.reevaluer_charges_fixes===true||String(d.reevaluer_charges_fixes)==='true';normaliserFractionPlanV46_(d);d.dernier_recalcul=new Date().toISOString();if(d.nature_action==='rembourser'&&!d.categorie)d.categorie='Crédits';enregistrerActionPlanV3(d);if(d.impact_confirme&&d.reevaluer_charges_fixes&&d.source_type==='charge_fixe'&&d.nature_action==='supprimer')cloturerChargeFixeDepuisActionV3(d.id,d.date_effet);recalculerPlanBudgetSoft_('action');return chargerPlanActionsV4();}
function enregistrerEvenementPlanV4(d){assurerPlanActionsV4_();d=Object.assign({},d||{});d.libelle=String(d.libelle||'').trim();if(!d.libelle)throw new Error('Le libellé de l’événement est obligatoire.');d.montant=Math.abs(Number(d.montant||0));if(!d.montant)throw new Error('Le montant doit être supérieur à zéro.');d.categorie=String(d.categorie||'').trim();normaliserFractionPlanV46_(d);d.recurrence=d.fractionne?d.periodicite_fractionnement:String(d.recurrence||'ponctuel');d.statut=String(d.statut||'Prévu');d.certitude=String(d.certitude||'certaine');d.dernier_recalcul=new Date().toISOString();upsertDynamiquePlanV4_('Plan_Evenements',d);recalculerPlanBudgetSoft_('evenement');return chargerPlanActionsV4();}
function supprimerElementPlanV4(type,id){assurerPlanActionsV4_();if(type==='action')supprimerActionPlanV3(id);else supprimerElementPlan(type,id);recalculerPlanBudgetSoft_('suppression_'+type);return chargerPlanActionsV4();}
function rechercherSourceActionV4(terme){const base=rechercherSourceActionV3(terme)||[];return serialiserCerberePourClient_(base.map(x=>{let cat='';try{if(x.type==='charge_fixe'){const r=lireTable_('Charges_fixes').find(y=>String(y.id)===String(x.id));cat=String(r&&r.categorie||'');}else if(x.type==='credit')cat='Crédits';else if(x.type==='operation'){const r=lireTable_('Operations').find(y=>String(y.id)===String(x.id));cat=String(r&&r.categorie||'');}}catch(e){}return Object.assign({},x,{categorie:cat});}));}
function capitalSourcePlanV4_(type,id){let row=null;if(type==='credit')row=lireTable_('Credits').find(x=>String(x.id)===String(id));if(!row&&type==='dette'){try{row=lireTable_('Dettes').find(x=>String(x.id)===String(id));}catch(e){}}if(!row)return 0;for(const k of ['capital_restant','capital_restant_du','reste_du','montant_restant','solde','capital']){const n=Math.abs(Number(row[k]||0));if(n>0)return n;}return 0;}
function proposerResolutionSourceV4(sourceType,sourceId,mois,reels){return calculerResolutionV4_(capitalSourcePlanV4_(String(sourceType||''),String(sourceId||'')),mois,reels||[]);}
function proposerResolutionActionV4(actionId,mois,reels){assurerPlanActionsV4_();const a=lireFeuilleDynamiquePlan_('Plan_Actions').find(x=>String(x.id)===String(actionId));if(!a)throw new Error('Action introuvable.');return calculerResolutionV4_(capitalSourcePlanV4_(a.source_type,a.source_id),mois,reels||[]);}
function periodesPlanV4_(){try{if(typeof construirePeriodesCerbereV2_==='function')return construirePeriodesCerbereV2_().map((p,i)=>({index:i+1,periode:p}));}catch(e){}return [];}
function calculerResolutionV4_(capital,mois,reels){mois=Math.max(1,Math.min(6,Number(mois||4)));capital=Math.abs(Number(capital||0));reels=Array.isArray(reels)?reels:[];const cerbere=typeof chargerCerbereV33==='function'?chargerCerbereV33():chargerCerbereV3(),ps=cerbere&&cerbere.ok?(cerbere.periodes||[]).slice(0,mois):[],deja=reels.reduce((s,x)=>s+Math.max(0,Number(x||0)),0),reste=Math.max(0,capital-deja),dispo=ps.reduce((s,p)=>s+Math.max(0,Number(p.resteAVentiler!=null?p.resteAVentiler:p.disponibleRestant!=null?p.disponibleRestant:p.margeStructurelle||0)),0);let restant=reste;const echeancier=ps.map((p,i)=>{const reel=Math.max(0,Number(reels[i]||0));if(reel>0)return {periode:i+1,date:p.periode&&p.periode.debut||'',libelle:p.periode&&p.periode.libelle||('P'+(i+1)),capacite:Math.max(0,Number(p.resteAVentiler!=null?p.resteAVentiler:p.disponibleRestant!=null?p.disponibleRestant:p.margeStructurelle||0)),montant_prevu:0,montant_reel:reel,statut:'Réalisé'};const nb=Math.max(1,ps.length-i),capa=Math.max(0,Number(p.resteAVentiler!=null?p.resteAVentiler:p.disponibleRestant!=null?p.disponibleRestant:p.margeStructurelle||0)),cible=Math.ceil((restant/nb)*100)/100,m=Math.min(restant,capa,cible);restant=Math.max(0,restant-m);return {periode:i+1,date:p.periode&&p.periode.debut||'',libelle:p.periode&&p.periode.libelle||('P'+(i+1)),capacite:capa,montant_prevu:Math.round(m*100)/100,montant_reel:0,statut:'À valider'};});return serialiserCerberePourClient_({capital_restant:capital,capital_deja_regle:deja,reste_a_regler:Math.max(0,capital-deja),mois,disponibilites_mobilisables:Math.round(dispo*100)/100,soutenable:capital>0&&restant<=0,non_couvert:Math.round(restant*100)/100,echeancier,etapes:[]});}
function rechercherOperationsEvenementV4(d){d=d||{};const id=String(d.id||d.event_id||d.source_id||'').trim();if(id&&typeof listerCandidatsRapprochementBudgetSoft==='function')return listerCandidatsRapprochementBudgetSoft({type:'evenement',previsionnel_id:id});const montant=Math.abs(Number(d.montant||0)),date=d.date_effet?new Date(d.date_effet):null,cat=String(d.categorie||'');let ops=lireTable_('Operations').filter(o=>Number(o.montant||0)<0);ops=ops.map(o=>{const om=Math.abs(Number(o.montant||0)),od=new Date(o.date_comptable||o.date||o.date_operation||0),jours=date&&!isNaN(date)&&!isNaN(od)?Math.abs(od-date)/86400000:99,score=Math.abs(om-montant)+(jours*2)+(cat&&String(o.categorie||'')!==cat?50:0);return {id:o.id||'',libelle:o.libelle||'',montant:om,date:o.date_comptable||o.date||o.date_operation||'',categorie:o.categorie||'',score};}).sort((a,b)=>a.score-b.score).slice(0,12);return serialiserCerberePourClient_(ops);}
function rapprocherEvenementV4(eventId,operationId){if(typeof rapprocherPrevisionnelReelBudgetSoft==='function')return rapprocherPrevisionnelReelBudgetSoft({type:'evenement',previsionnel_id:eventId,operation_id:operationId});throw new Error('Moteur unique de rapprochement indisponible.');}
function ajouterMoisPlanV4_(date,n){const d=new Date(date);if(isNaN(d))return '';const jour=d.getDate();d.setDate(1);d.setMonth(d.getMonth()+n);const fin=new Date(d.getFullYear(),d.getMonth()+1,0).getDate();d.setDate(Math.min(jour,fin));return Utilities.formatDate(d,Session.getScriptTimeZone(),'yyyy-MM-dd');}
function ajouterAnneesPlanV4_(date,n){const d=new Date(date);if(isNaN(d))return '';d.setFullYear(d.getFullYear()+n);return Utilities.formatDate(d,Session.getScriptTimeZone(),'yyyy-MM-dd');}
function occurrencesMontantPlanV46_(obj,montant,date){const n=yesPlanV4_(obj.fractionne)?Math.max(2,Number(obj.nombre_fois||2)):1,period=String(obj.periodicite_fractionnement||'mensuel'),total=Math.abs(Number(montant||0)),base=Math.floor((total/n)*100)/100,reste=Math.round((total-base*n)*100)/100,out=[];for(let i=0;i<n;i++){const m=Math.round((base+(i===n-1?reste:0))*100)/100;const d=i===0?date:(period==='annuel'?ajouterAnneesPlanV4_(date,i):ajouterMoisPlanV4_(date,i));out.push({index:i+1,total:n,montant:m,date:d});}return out;}
function occurrencesEvenementV4_(e){return occurrencesMontantPlanV46_(e,e.montant,e.date_effet);}
function occurrencesActionV46_(a){return occurrencesMontantPlanV46_(a,a.impact_montant,a.date_effet);}
function construireLignesPrevisionnellesV4_(actions,evenements){const ps=periodesPlanV4_();const lignes=[];function pIndex(date){const d=new Date(date);if(isNaN(d))return 0;const i=ps.findIndex(x=>{const a=new Date(x.periode.debut),b=new Date(x.periode.fin);return d>=a&&d<=b;});return i>=0?i+1:0;}(actions||[]).forEach(a=>{if(!yesPlanV4_(a.impact_confirme)||['Abandonnée','Annulée'].includes(String(a.statut)))return;const et=(a.etapes||[]).filter(e=>Number(e.montant_prevu||0)>0);if(et.length)et.forEach(e=>lignes.push({source:'Action',source_id:a.id,libelle:a.libelle,categorie:a.categorie||'',mode_paiement:a.mode_paiement||'',montant:Number(e.montant_prevu||0),date:e.date_prevue||'',periode:pIndex(e.date_prevue)}));else occurrencesActionV46_(a).forEach(o=>lignes.push({source:'Action',source_id:a.id,occurrence:o.index,occurrences:o.total,libelle:a.libelle,categorie:a.categorie||'',mode_paiement:a.mode_paiement||'',montant:o.montant,date:o.date,periode:pIndex(o.date)}));});(evenements||[]).forEach(e=>{if(['Rapproché','Annulé','Réalisé'].includes(String(e.statut)))return;occurrencesEvenementV4_(e).forEach(o=>lignes.push({source:'Événement',source_id:e.id,occurrence:o.index,occurrences:o.total,libelle:e.libelle,categorie:e.categorie||'',mode_paiement:e.mode_paiement||'',type:e.type||'',montant:e.type==='depense'?o.montant:-o.montant,date:o.date,periode:pIndex(o.date)}));});return lignes;}
function yesPlanV4_(v){return v===true||String(v)==='true';}
function recalculerPlanBudgetSoft_(origine){if(typeof invaliderProjectionBudgetSoft_==='function')return invaliderProjectionBudgetSoft_(origine);const props=PropertiesService.getDocumentProperties(),maintenant=new Date().toISOString();props.setProperty('PLAN_DERNIER_RECALCUL',maintenant);props.setProperty('PLAN_DERNIERE_ORIGINE',String(origine||'inconnue'));props.setProperty('BUDGETSOFT_PROJECTION_DIRTY','true');props.setProperty('BUDGETSOFT_PROJECTION_DIRTY_LE',maintenant);return {ok:true,invalidee:true,origine:String(origine||'inconnue')};}
