const REIMPORT_LOG_SHEET='Reimport_nettoyage';
const REIMPORT_LOG_HEADERS=['id','date','statut','operation_id','date_operation','montant','ancien_libelle','nouveau_libelle','categorie_conservee','note'];
function initialiserReimportLog_(){const ss=SpreadsheetApp.getActiveSpreadsheet();let f=ss.getSheetByName(REIMPORT_LOG_SHEET);if(!f)f=ss.insertSheet(REIMPORT_LOG_SHEET);if(f.getLastRow()===0)f.getRange(1,1,1,REIMPORT_LOG_HEADERS.length).setValues([REIMPORT_LOG_HEADERS]);f.setFrozenRows(1);return f;}
function cleReimportDate_(v){const d=new Date(v);return isNaN(d)?'':Utilities.formatDate(d,Session.getScriptTimeZone(),'yyyy-MM-dd');}
function dateReimport_(v){const d=new Date(v);return isNaN(d)?null:new Date(d.getFullYear(),d.getMonth(),d.getDate());}
function ecartJoursReimport_(a,b){const da=dateReimport_(a),db=dateReimport_(b);return(!da||!db)?999:Math.round(Math.abs(da-db)/86400000);}
function normalReimport_(s){return normaliserTexteBanque_(String(s||'')).replace(/\b(?:carte|cb|prelevement|virement|sepa|paiement)\b/g,' ').replace(/\s+/g,' ').trim();}
function cleReimportMontant_(v){return Math.round(Math.abs(Number(v||0))*100);}
function scoreReimport_(nouvelle,ancienne){let s=0;const jours=ecartJoursReimport_(nouvelle.date,ancienne.date);if(jours===0)s+=55;else if(jours===1)s+=48;else if(jours===2)s+=42;if(cleReimportMontant_(nouvelle.montant)===cleReimportMontant_(ancienne.montant))s+=35;const a=normalReimport_(nouvelle.libelle),src=(typeof sourceAudit_==='function'?sourceAudit_(ancienne).libelle:ancienne.libelle)||ancienne.libelle,b=normalReimport_(src);if(a&&b){if(a===b)s+=15;else if(a.includes(b)||b.includes(a))s+=11;else{const mots=a.split(' ').filter(x=>x.length>3),communs=mots.filter(x=>b.includes(x));s+=Math.min(10,communs.length*2);}}return s;}
function analyserReimportNettoyage(lignes,compte){const nouvelles=(lignes||[]).filter(x=>x&&x.valide!==false&&x.date&&Number.isFinite(Number(x.montant))),ops=lireTable_('Operations').filter(o=>String(o.compte)===String(compte)&&!String(o.commentaire||'').includes('[RECURRENCE:')),indexMontant={};ops.forEach(o=>{const k=cleReimportMontant_(o.montant);(indexMontant[k]||(indexMontant[k]=[])).push(o);});const resultats=nouvelles.map(n=>{const pool=(indexMontant[cleReimportMontant_(n.montant)]||[]).filter(o=>ecartJoursReimport_(n.date,o.date)<=2),candidats=pool.map(o=>({o,score:scoreReimport_(n,o),ecartJours:ecartJoursReimport_(n.date,o.date)})).filter(x=>x.score>=80).sort((a,b)=>b.score-a.score),meilleur=candidats[0],second=candidats[1];let statut='Nouveau';if(meilleur){const marge=second?meilleur.score-second.score:99;statut=(meilleur.score>=90&&marge>=5)?'Correspondance sûre':'Ambigu';}return{date:n.date,montant:n.montant,libelle:n.libelle||'',commentaire:n.commentaire||n.details||'',type:n.type||'',statut,score:meilleur?.score||0,ecart_jours:meilleur?.ecartJours??'',operation_id:meilleur?.o?.id||'',ancien_libelle:meilleur?.o?.libelle||'',ancienne_date:meilleur?.o?.date||'',categorie:meilleur?.o?.categorie||'',ancien_type:meilleur?.o?.type||'',compte,candidats:candidats.slice(0,3).map(c=>({id:c.o.id,libelle:c.o.libelle,date:c.o.date,montant:c.o.montant,categorie:c.o.categorie||'',score:c.score,ecart_jours:c.ecartJours}))};});return{total:resultats.length,sures:resultats.filter(x=>x.statut==='Correspondance sûre').length,ambigues:resultats.filter(x=>x.statut==='Ambigu').length,nouvelles:resultats.filter(x=>x.statut==='Nouveau').length,lignes:resultats};}
function appliquerReimportNettoyage(lignes){const aTraiter=(lignes||[]).filter(n=>n.statut==='Correspondance sûre'&&n.operation_id),ambigues=(lignes||[]).filter(n=>n.statut==='Ambigu').length,nouvelles=(lignes||[]).filter(n=>n.statut==='Nouveau').length;if(!aTraiter.length)return{remplacees:0,ambigues,nouvelles};const ops=lireTable_('Operations'),parId=Object.fromEntries(ops.map(o=>[String(o.id),o])),log=initialiserReimportLog_(),now=new Date().toISOString(),logs=[];let remplacees=0;aTraiter.forEach(n=>{const o=parId[String(n.operation_id)];if(!o)return;const nouveauComment=[n.commentaire||'','[REIMPORT_NETTOYAGE:'+now+']'].filter(Boolean).join(' ');enregistrerLigne('Operations',{id:o.id,date:n.date||o.date,libelle:n.libelle||o.libelle,categorie:o.categorie||'',compte:o.compte,montant:Math.abs(Number(n.montant||o.montant||0)),type:o.type||n.type||'depense',commentaire:nouveauComment,cree_le:o.cree_le||''});logs.push([Utilities.getUuid(),now,'Remplacé',o.id,n.date,n.montant,o.libelle,n.libelle,o.categorie||'','Catégorie et type historiques conservés']);remplacees++;});if(logs.length)log.getRange(log.getLastRow()+1,1,logs.length,REIMPORT_LOG_HEADERS.length).setValues(logs);return{remplacees,ambigues,nouvelles};}
