const BUDGETSOFT_DASHBOARD_SEMANTICS_FINAL_VERSION='2026-09-13.1';

function milieuJourDashboardProjection20260907_(debut,fin){const a=new Date(String(debut||'')+'T12:00:00'),b=new Date(String(fin||'')+'T12:00:00');if(isNaN(a.getTime())||isNaN(b.getTime()))return'';return Utilities.formatDate(new Date(a.getTime()+Math.floor((b.getTime()-a.getTime())/2)),Session.getScriptTimeZone(),'yyyy-MM-dd');}

function appliquerProjectionTresorerieCycleSuivantDashboard20260907_(r){
  const s=r&&r.cycleSuivant;if(!s||!s.debut||!s.fin||typeof chargerSnapshotGlobalBudgetSoft20260906!=='function')return r;
  let snap=null;try{snap=chargerSnapshotGlobalBudgetSoft20260906();}catch(e){return r;}
  const etat=snap&&snap.disponible&&snap.etat,proj=etat&&etat.modules&&etat.modules.projectionEtendue;if(!etat||etat.ok!==true||!proj||proj.ok===false)return r;
  if(typeof pointProjectionTresorerieUnifiee20260907_!=='function'||typeof resumePeriodeTresorerieUnifiee20260907_!=='function')return r;
  const mi=milieuJourDashboardProjection20260907_(s.debut,s.fin),resume=resumePeriodeTresorerieUnifiee20260907_(proj,s.debut,s.fin);
  s.soldeJ1=pointProjectionTresorerieUnifiee20260907_(proj,s.debut);s.soldeMiCycle=pointProjectionTresorerieUnifiee20260907_(proj,mi);s.soldeFinCycle=pointProjectionTresorerieUnifiee20260907_(proj,s.fin);s.revenusPrevisionnels=resume.recettes;s.depensesPrevisionnelles=resume.depenses;delete s.depensesBudgetees;s.projectionTresorerieDisponible=true;s.sourceProjection='tresorerie_unifiee_snapshot';s.versionProjection=proj.version||'';s.revisionProjection=etat.revisionBudgetSoft||'';s.nombreLignesProjectionCycle=resume.nombreLignes;r.provenance=r.provenance||{};r.provenance.previsionsCycleSuivant='même projectionEtendue publiée que Comptes et Cerbère';return r;
}

/**
 * Adaptateur sémantique intermodule : Dashboard ne calcule ni P ni EP.
 * Il consomme le même module Cerbère du snapshot global : P = indicateur,
 * EP = décision. Les anciens alias pilotableDisponible/pilotableParJour sont
 * conservés mais pointent explicitement vers EP pour ne pas casser les vues.
 */
function appliquerSemantiqueEpDashboard20260913_(r){
  if(!r||typeof chargerSnapshotGlobalBudgetSoft20260906!=='function')return r;
  let snap=null;try{snap=chargerSnapshotGlobalBudgetSoft20260906();}catch(e){return r;}
  const etat=snap&&snap.disponible&&snap.etat,m=etat&&etat.modules||{},cer=m.cerbere||null;if(!cer||cer.ok===false)return r;
  if(typeof enrichirEnvelopePilotableBudgetSoft20260913_==='function')try{enrichirEnvelopePilotableBudgetSoft20260913_(cer);}catch(e){}
  const ps=Array.isArray(cer.periodes)?cer.periodes:[],p1=ps[0],p2=ps[1];
  const publier=(cible,p,index)=>{if(!cible||!p)return;const v=p.v37||{},c=v.cockpit20260902||{},ep=p.enveloppePilotable||(typeof calculerEnvelopePilotableBudgetSoft20260913_==='function'?calculerEnvelopePilotableBudgetSoft20260913_(p):null);if(!ep)return;const soutenable=Number(c.pSoutenable!=null?c.pSoutenable:(c.p1Total||0)),consomme=Number(ep.consomme||0),epTotal=Number(ep.total||0),epDisp=Number(ep.reste||0),pDisp=Number(c.pDisponible!=null?c.pDisponible:(soutenable-consomme));cible.ep=epTotal;cible.epDisponible=epDisp;cible.epConsomme=consomme;cible.epSource=String(ep.source||'');cible.pSoutenable=soutenable;cible.pDisponible=pDisp;cible.ecartEpP=Math.round((epTotal-soutenable)*100)/100;cible.proprietaireEp=String(typeof BUDGETSOFT_EP_OWNER_20260913!=='undefined'?BUDGETSOFT_EP_OWNER_20260913:'');cible.proprietaireP='diagnostic.p1Doctrine20260912 / Cerbère';cible.pilotableDisponible=epDisp;const fin=new Date(p.periode&&p.periode.fin||0),now=new Date(),jours=!isNaN(fin)?Math.max(1,Math.ceil((Date.UTC(fin.getFullYear(),fin.getMonth(),fin.getDate())-Date.UTC(now.getFullYear(),now.getMonth(),now.getDate()))/86400000)+1):1;cible.pilotableParJour=Math.round((epDisp/jours)*100)/100;cible.pilotableSemantique='alias EP disponible';if(index===1){cible.epPrevisionnel=epTotal;cible.p2Previsionnel=soutenable;cible.ecartEpP2=cible.ecartEpP;cible.cbDejaEngagee=Number(c.cbDejaEngagee||0);cible.cbEpEstimee=Number(c.cbEpEstimee||0);cible.reportCbCycle=Number(c.reportCbCycle||0);}};
  publier(r.courtTerme||{},p1,0);publier(r.cycleSuivant||{},p2,1);
  r.provenance=r.provenance||{};r.provenance.enveloppePilotable='BudgetSoftEnvelopePilotable20260913 · décision par molettes';r.provenance.soutenabilite='Cerbère P · lecture seule';r.versionEp=BUDGETSOFT_EP_20260913_VERSION;return r;
}

function corrigerSemantiqueDashboardBudgetSoft20260907_(d){if(!d||typeof d!=='object')return d;let r=d;try{r=JSON.parse(JSON.stringify(d));}catch(e){}r=appliquerProjectionTresorerieCycleSuivantDashboard20260907_(r);r=appliquerSemantiqueEpDashboard20260913_(r);r.versionSemantique=BUDGETSOFT_DASHBOARD_SEMANTICS_FINAL_VERSION;return r;}
function chargerDashboardSyntheseV3BudgetSoft20260907(){return corrigerSemantiqueDashboardBudgetSoft20260907_(chargerDashboardSyntheseBudgetSoft20260907());}
function auditerSemantiqueDashboardBudgetSoft20260907(){const d=chargerDashboardSyntheseV3BudgetSoft20260907(),c=d&&d.courtTerme||{},s=d&&d.cycleSuivant||{},r={ok:!!(d&&d.ok!==false),version:d&&d.version||'',versionSemantique:d&&d.versionSemantique||'',courant:{ep:c.ep,epDisponible:c.epDisponible,p1:c.pSoutenable,p1Disponible:c.pDisponible,ecartEpP1:c.ecartEpP,pilotableAlias:c.pilotableDisponible},cycleSuivant:{ep:s.ep,p2:s.pSoutenable,ecartEpP2:s.ecartEpP,cbDejaEngagee:s.cbDejaEngagee,cbEpEstimee:s.cbEpEstimee,reportCbCycle:s.reportCbCycle,sourceProjection:s.sourceProjection||'',soldeJ1:s.soldeJ1,soldeMiCycle:s.soldeMiCycle,soldeFinCycle:s.soldeFinCycle},provenance:d&&d.provenance||{}};r.ok=r.ok&&Math.abs(Number(c.pilotableDisponible||0)-Number(c.epDisponible||0))<=.01;console.log('[AUDIT Dashboard sémantique EP/P] '+JSON.stringify(r));return r;}

function auditerFrontiereHistoriqueDashboardBudgetSoft20260909(){
  const d=chargerDashboardSyntheseBudgetSoft20260907(),p=d&&d.cyclePrecedent||{},debut=String(p.debut||'');let sources=null;try{sources=chargerToutesLesDonnees();}catch(e){sources=null;}let ops=sources&&Array.isArray(sources.Operations)?sources.Operations:[];if(typeof dedoublonnerOperationsCartesBudgetSoft_==='function')try{ops=dedoublonnerOperationsCartesBudgetSoft_(ops);}catch(e){}const snap=typeof chargerSnapshotGlobalBudgetSoft20260906==='function'?chargerSnapshotGlobalBudgetSoft20260906():null,etat=snap&&snap.disponible&&snap.etat,tres=etat&&etat.modules&&etat.modules.tresorerieComptable,cles=new Set();(tres&&tres.comptes||[]).forEach(c=>{cles.add(String(c.id||''));cles.add(String(c.nom||''));});let netJourDebut=0,nombre=0;const details=[];ops.forEach(o=>{if(typeof operationReelleCanoniqueBudgetSoft20260906_==='function'&&!operationReelleCanoniqueBudgetSoft20260906_(o))return;if(cles.size&&!cles.has(String(o&&o.compte||'')))return;let jour='';try{const dt=typeof dateComptableCanonBudgetSoft20260906_==='function'?dateComptableCanonBudgetSoft20260906_(o):null;jour=dt?Utilities.formatDate(dt,Session.getScriptTimeZone(),'yyyy-MM-dd'):'';}catch(e){jour='';}if(jour!==debut)return;const m=typeof montantSigneCanoniqueBudgetSoft20260906_==='function'?Number(montantSigneCanoniqueBudgetSoft20260906_(o)||0):Number(o&&o.montant||0);if(!Number.isFinite(m)||Math.abs(m)<.000001)return;netJourDebut+=m;nombre++;details.push({id:String(o&&o.id||''),libelle:String(o&&o.libelle||o&&o.libelle_bancaire||''),montant:Math.round(m*100)/100});});netJourDebut=Math.round(netJourDebut*100)/100;const ecart=Math.round(Number(p.ecartReconciliation||0)*100)/100,frontiereExpliqueEcart=Math.abs(Math.round((ecart+netJourDebut)*100)/100)<=.01,r={ok:frontiereExpliqueEcart,debut,fin:String(p.fin||''),soldeJ1:p.soldeJ1,soldeFinCycle:p.soldeFinCycle,netOperations:p.netOperations,ecartReconciliation:ecart,netJourDebut,nombreOperationsJourDebut:nombre,frontiereExpliqueEcart,details};console.log('[AUDIT Dashboard frontière historique] '+JSON.stringify(r));return r;
}
